cls

cr ." a-"         a- key drop
cr ." a="         a= key drop
cr ." ai-"        ai- key drop
cr ." ai="        ai= key drop
cr ." ai["        ai[ key drop
cr ." ai]"        ai] key drop
cr ." an-"        an- key drop
cr ." ang-"       ang- key drop
cr ." ang="       ang= key drop
cr ." ang]"       ang] key drop
cr ." an["        an[ key drop
cr ." an]"        an] key drop
cr ." au-"        au- key drop
cr ." au="        au= key drop
cr ." au["        au[ key drop
cr ." au]"        au] key drop
cr ." a["         a[ key drop
cr ." a]"         a] key drop
cr ." ba'"        ba' key drop
cr ." ba-"        ba- key drop
cr ." ba="        ba= key drop
cr ." bai'"       bai' key drop
cr ." bai-"       bai- key drop
cr ." bai="       bai= key drop
cr ." bai["       bai[ key drop
cr ." bai]"       bai] key drop
cr ." ban-"       ban- key drop
cr ." bang-1"     bang-1 key drop
cr ." bang["      bang[ key drop
cr ." bang]"      bang] key drop
cr ." ban["       ban[ key drop
cr ." ban]"       ban] key drop
cr ." bau-"       bau- key drop
cr ." bau="       bau= key drop
cr ." bau["       bau[ key drop
cr ." bau]"       bau] key drop
cr ." ba["        ba[ key drop
cr ." ba]"        ba] key drop
cr ." bei'"       bei' key drop
cr ." bei-"       bei- key drop
cr ." bei["       bei[ key drop
cr ." bei]"       bei] key drop
cr ." ben'"       ben' key drop
cr ." ben-"       ben- key drop
cr ." beng-"      beng- key drop
cr ." beng="      beng= key drop
cr ." beng["      beng[ key drop
cr ." beng]"      beng] key drop
cr ." ben["       ben[ key drop
cr ." ben]"       ben] key drop
cr ." bi-"        bi- key drop
cr ." bi="        bi= key drop
cr ." bian'"      bian' key drop
cr ." bian-"      bian- key drop
cr ." bian["      bian[ key drop
cr ." bian]"      bian] key drop
cr ." biau-"      biau- key drop
cr ." biau["      biau[ key drop
cr ." biau]"      biau] key drop
cr ." bie-"       bie- key drop
cr ." bie="       bie= key drop
cr ." bie["       bie[ key drop
cr ." bie]"       bie] key drop
cr ." bin-"       bin- key drop
cr ." bing-"      bing- key drop
cr ." bing["      bing[ key drop
cr ." bing]"      bing] key drop
cr ." bin]"       bin] key drop
cr ." bi["        bi[ key drop
cr ." bi]"        bi] key drop
cr ." bo'"        bo' key drop
cr ." bo-"        bo- key drop
cr ." bo="        bo= key drop
cr ." bo["        bo[ key drop
cr ." bo]"        bo] key drop
cr ." bu'"        bu' key drop
cr ." bu-"        bu- key drop
cr ." bu="        bu= key drop
cr ." bu["        bu[ key drop
cr ." bu]"        bu] key drop
cr ." cha-"       cha- key drop
cr ." cha="       cha= key drop
cr ." chai-"      chai- key drop
cr ." chai="      chai= key drop
cr ." chai["      chai[ key drop
cr ." chai]"      chai] key drop
cr ." chan-"      chan- key drop
cr ." chan="      chan= key drop
cr ." chang-"     chang- key drop
cr ." chang="     chang= key drop
cr ." chang["     chang[ key drop
cr ." chang]"     chang] key drop
cr ." chan["      chan[ key drop
cr ." chan]"      chan] key drop
cr ." chau-"      chau- key drop
cr ." chau="      chau= key drop
cr ." chau["      chau[ key drop
cr ." chau]"      chau] key drop
cr ." cha["       cha[ key drop
cr ." cha]"       cha] key drop
cr ." che-"       che- key drop
cr ." chen'"      chen' key drop
cr ." chen-"      chen- key drop
cr ." chen="      chen= key drop
cr ." cheng-"     cheng- key drop
cr ." cheng="     cheng= key drop
cr ." cheng["     cheng[ key drop
cr ." cheng]"     cheng] key drop
cr ." chen]"      chen] key drop
cr ." che["       che[ key drop
cr ." che]"       che] key drop
cr ." chi'"       chi' key drop
cr ." chi-"       chi- key drop
cr ." chi="       chi= key drop
cr ." chia-"      chia- key drop
cr ." chian'"     chian' key drop
cr ." chian-"     chian- key drop
cr ." chian="     chian= key drop
cr ." chiang-"    chiang- key drop
cr ." chiang="    chiang= key drop
cr ." chiang["    chiang[ key drop
cr ." chiang]"    chiang] key drop
cr ." chian["     chian[ key drop
cr ." chian]"     chian] key drop
cr ." chiau-"     chiau- key drop
cr ." chiau="     chiau= key drop
cr ." chiau["     chiau[ key drop
cr ." chiau]"     chiau] key drop
cr ." chia["      chia[ key drop
cr ." chia]"      chia] key drop
cr ." chie-"      chie- key drop
cr ." chie="      chie= key drop
cr ." chie["      chie[ key drop
cr ." chie]"      chie] key drop
cr ." chin'"      chin' key drop
cr ." chin-"      chin- key drop
cr ." chin="      chin= key drop
cr ." ching'"     ching' key drop
cr ." ching-"     ching- key drop
cr ." ching="     ching= key drop
cr ." ching["     ching[ key drop
cr ." ching]"     ching] key drop
cr ." chin["      chin[ key drop
cr ." chin]"      chin] key drop
cr ." chiou-"     chiou- key drop
cr ." chiou="     chiou= key drop
cr ." chi["       chi[ key drop
cr ." chi]"       chi] key drop
cr ." chou'"      chou' key drop
cr ." chou-"      chou- key drop
cr ." chou="      chou= key drop
cr ." chou["      chou[ key drop
cr ." chou]"      chou] key drop
cr ." chu'"       chu' key drop
cr ." chu-"       chu- key drop
cr ." chu="       chu= key drop
cr ." chua-"      chua- key drop
cr ." chuai-"     chuai- key drop
cr ." chuai["     chuai[ key drop
cr ." chuai]"     chuai] key drop
cr ." chuan-"     chuan- key drop
cr ." chuan="     chuan= key drop
cr ." chuang-"    chuang- key drop
cr ." chuang="    chuang= key drop
cr ." chuang["    chuang[ key drop
cr ." chuang]"    chuang] key drop
cr ." chuan["     chuan[ key drop
cr ." chuan]"     chuan] key drop
cr ." chui-"      chui- key drop
cr ." chui="      chui= key drop
cr ." chun-"      chun- key drop
cr ." chun="      chun= key drop
cr ." chung-"     chung- key drop
cr ." chung="     chung= key drop
cr ." chung["     chung[ key drop
cr ." chung]"     chung] key drop
cr ." chun["      chun[ key drop
cr ." chuo-"      chuo- key drop
cr ." chuo]"      chuo] key drop
cr ." chu["       chu[ key drop
cr ." chu]"       chu] key drop
cr ." chy-"       chy- key drop
cr ." chy="       chy= key drop
cr ." chyu'"      chyu' key drop
cr ." chyu-"      chyu- key drop
cr ." chyu="      chyu= key drop
cr ." chyuan-"    chyuan- key drop
cr ." chyuan="    chyuan= key drop
cr ." chyuan["    chyuan[ key drop
cr ." chyuan]"    chyuan] key drop
cr ." chyue-"     chyue- key drop
cr ." chyue="     chyue= key drop
cr ." chyue]"     chyue] key drop
cr ." chyun-"     chyun- key drop
cr ." chyun="     chyun= key drop
cr ." chyung="    chyung= key drop
cr ." chyu["      chyu[ key drop
cr ." chyu]"      chyu] key drop
cr ." chy["       chy[ key drop
cr ." chy]"       chy] key drop
cr ." da'"        da' key drop
cr ." da-"        da- key drop
cr ." da="        da= key drop
cr ." dai'"       dai' key drop
cr ." dai-"       dai- key drop
cr ." dai["       dai[ key drop
cr ." dai]"       dai] key drop
cr ." dan-"       dan- key drop
cr ." dang-"      dang- key drop
cr ." dang["      dang[ key drop
cr ." dang]"      dang] key drop
cr ." dan["       dan[ key drop
cr ." dan]"       dan] key drop
cr ." dau'"       dau' key drop
cr ." dau-"       dau- key drop
cr ." dau["       dau[ key drop
cr ." dau]"       dau] key drop
cr ." da["        da[ key drop
cr ." da]"        da] key drop
cr ." de'"        de' key drop
cr ." de="        de= key drop
cr ." dei["       dei[ key drop
cr ." deng-"      deng- key drop
cr ." deng["      deng[ key drop
cr ." deng]"      deng] key drop
cr ." den]"       den] key drop
cr ." di'"        di' key drop
cr ." di-"        di- key drop
cr ." di="        di= key drop
cr ." dian'"      dian' key drop
cr ." dian-"      dian- key drop
cr ." dian["      dian[ key drop
cr ." dian]"      dian] key drop
cr ." diau'"      diau' key drop
cr ." diau-"      diau- key drop
cr ." diau]"      diau] key drop
cr ." die-"       die- key drop
cr ." die="       die= key drop
cr ." ding-"      ding- key drop
cr ." ding["      ding[ key drop
cr ." ding]"      ding] key drop
cr ." diou-"      diou- key drop
cr ." di["        di[ key drop
cr ." di]"        di] key drop
cr ." dou-"       dou- key drop
cr ." dou["       dou[ key drop
cr ." dou]"       dou] key drop
cr ." du'"        du' key drop
cr ." du-"        du- key drop
cr ." du="        du= key drop
cr ." duan-"      duan- key drop
cr ." duan["      duan[ key drop
cr ." duan]"      duan] key drop
cr ." duei-"      duei- key drop
cr ." duei]"      duei] key drop
cr ." dun-"       dun- key drop
cr ." dung-"      dung- key drop
cr ." dung["      dung[ key drop
cr ." dung]"      dung] key drop
cr ." dun["       dun[ key drop
cr ." dun]"       dun] key drop
cr ." duo'"       duo' key drop
cr ." duo-"       duo- key drop
cr ." duo="       duo= key drop
cr ." duo["       duo[ key drop
cr ." duo]"       duo] key drop
cr ." du["        du[ key drop
cr ." du]"        du] key drop
cr ." e-"         e- key drop
cr ." e="         e= key drop
cr ." ei="        ei= key drop
cr ." ei["        ei[ key drop
cr ." ei]"        ei] key drop
cr ." en-"        en- key drop
cr ." eng'"       eng' key drop
cr ." eng="       eng= key drop
cr ." eng["       eng[ key drop
cr ." eng]"       eng] key drop
cr ." en]"        en] key drop
cr ." er="        er= key drop
cr ." er["        er[ key drop
cr ." er]"        er] key drop
cr ." e["         e[ key drop
cr ." e]"         e] key drop
cr ." fa'"        fa' key drop
cr ." fa-"        fa- key drop
cr ." fa="        fa= key drop
cr ." fan'"       fan' key drop
cr ." fan-"       fan- key drop
cr ." fan="       fan= key drop
cr ." fang'"      fang' key drop
cr ." fang-"      fang- key drop
cr ." fang="      fang= key drop
cr ." fang["      fang[ key drop
cr ." fang]"      fang] key drop
cr ." fan["       fan[ key drop
cr ." fan]"       fan] key drop
cr ." fa["        fa[ key drop
cr ." fa]"        fa] key drop
cr ." fei-"       fei- key drop
cr ." fei="       fei= key drop
cr ." fei["       fei[ key drop
cr ." fei]"       fei] key drop
cr ." fen'"       fen' key drop
cr ." fen-"       fen- key drop
cr ." fen="       fen= key drop
cr ." feng-"      feng- key drop
cr ." feng="      feng= key drop
cr ." feng["      feng[ key drop
cr ." feng]"      feng] key drop
cr ." fen["       fen[ key drop
cr ." fen]"       fen] key drop
cr ." fo="        fo= key drop
cr ." fou["       fou[ key drop
cr ." fu'"        fu' key drop
cr ." fu-"        fu- key drop
cr ." fu="        fu= key drop
cr ." fu["        fu[ key drop
cr ." fu]"        fu] key drop
cr ." ga-"        ga- key drop
cr ." ga="        ga= key drop
cr ." gai-"       gai- key drop
cr ." gai["       gai[ key drop
cr ." gai]"       gai] key drop
cr ." gan-"       gan- key drop
cr ." gang'"      gang' key drop
cr ." gang-"      gang- key drop
cr ." gang["      gang[ key drop
cr ." gang]"      gang] key drop
cr ." gan["       gan[ key drop
cr ." gan]"       gan] key drop
cr ." gau-"       gau- key drop
cr ." gau["       gau[ key drop
cr ." gau]"       gau] key drop
cr ." ga]"        ga] key drop
cr ." ge'"        ge' key drop
cr ." ge-"        ge- key drop
cr ." ge="        ge= key drop
cr ." gei["       gei[ key drop
cr ." gen-"       gen- key drop
cr ." gen="       gen= key drop
cr ." geng-"      geng- key drop
cr ." geng["      geng[ key drop
cr ." geng]"      geng] key drop
cr ." gen["       gen[ key drop
cr ." gen]"       gen] key drop
cr ." ge["        ge[ key drop
cr ." ge]"        ge] key drop
cr ." gou-"       gou- key drop
cr ." gou["       gou[ key drop
cr ." gou]"       gou] key drop
cr ." gu'"        gu' key drop
cr ." gu-"        gu- key drop
cr ." gu="        gu= key drop
cr ." gua-"       gua- key drop
cr ." guai-"      guai- key drop
cr ." guai["      guai[ key drop
cr ." guai]"      guai] key drop
cr ." guan-"      guan- key drop
cr ." guang-"     guang- key drop
cr ." guang["     guang[ key drop
cr ." guang]"     guang] key drop
cr ." guan["      guan[ key drop
cr ." guan]"      guan] key drop
cr ." gua["       gua[ key drop
cr ." gua]"       gua] key drop
cr ." guei'"      guei' key drop
cr ." guei-"      guei- key drop
cr ." guei["      guei[ key drop
cr ." guei]"      guei] key drop
cr ." guen["      guen[ key drop
cr ." guen]"      guen] key drop
cr ." gung-"      gung- key drop
cr ." gung["      gung[ key drop
cr ." gung]"      gung] key drop
cr ." guo'"       guo' key drop
cr ." guo-"       guo- key drop
cr ." guo="       guo= key drop
cr ." guo["       guo[ key drop
cr ." guo]"       guo] key drop
cr ." gu["        gu[ key drop
cr ." gu]"        gu] key drop
cr ." ha'"        ha' key drop
cr ." ha-"        ha- key drop
cr ." ha="        ha= key drop
cr ." hai'"       hai' key drop
cr ." hai-"       hai- key drop
cr ." hai="       hai= key drop
cr ." hai["       hai[ key drop
cr ." hai]"       hai] key drop
cr ." han-"       han- key drop
cr ." han="       han= key drop
cr ." hang-"      hang- key drop
cr ." hang="      hang= key drop
cr ." hang]"      hang] key drop
cr ." han["       han[ key drop
cr ." han]"       han] key drop
cr ." hau-"       hau- key drop
cr ." hau="       hau= key drop
cr ." hau["       hau[ key drop
cr ." hau]"       hau] key drop
cr ." ha["        ha[ key drop
cr ." ha]"        ha] key drop
cr ." he'"        he' key drop
cr ." he-"        he- key drop
cr ." he="        he= key drop
cr ." hei-"       hei- key drop
cr ." hen="       hen= key drop
cr ." heng'"      heng' key drop
cr ." heng-"      heng- key drop
cr ." heng="      heng= key drop
cr ." heng]"      heng] key drop
cr ." hen["       hen[ key drop
cr ." hen]"       hen] key drop
cr ." he]"        he] key drop
cr ." hou'"       hou' key drop
cr ." hou-"       hou- key drop
cr ." hou="       hou= key drop
cr ." hou["       hou[ key drop
cr ." hou]"       hou] key drop
cr ." hu'"        hu' key drop
cr ." hu-"        hu- key drop
cr ." hu="        hu= key drop
cr ." hua'"       hua' key drop
cr ." hua-"       hua- key drop
cr ." hua="       hua= key drop
cr ." huai="      huai= key drop
cr ." huai]"      huai] key drop
cr ." huan-"      huan- key drop
cr ." huan="      huan= key drop
cr ." huang'"     huang' key drop
cr ." huang-"     huang- key drop
cr ." huang="     huang= key drop
cr ." huang["     huang[ key drop
cr ." huang]"     huang] key drop
cr ." huan["      huan[ key drop
cr ." huan]"      huan] key drop
cr ." hua["       hua[ key drop
cr ." hua]"       hua] key drop
cr ." huei'"      huei' key drop
cr ." huei-"      huei- key drop
cr ." huei="      huei= key drop
cr ." huei["      huei[ key drop
cr ." huei]"      huei] key drop
cr ." huen-"      huen- key drop
cr ." huen="      huen= key drop
cr ." huen]"      huen] key drop
cr ." hung-"      hung- key drop
cr ." hung="      hung= key drop
cr ." hung["      hung[ key drop
cr ." hung]"      hung] key drop
cr ." huo'"       huo' key drop
cr ." huo-"       huo- key drop
cr ." huo="       huo= key drop
cr ." huo["       huo[ key drop
cr ." huo]"       huo] key drop
cr ." hu["        hu[ key drop
cr ." hu]"        hu] key drop
cr ." i'"         i' key drop
cr ." i-"         i- key drop
cr ." i="         i= key drop
cr ." ia'"        ia' key drop
cr ." ia-"        ia- key drop
cr ." ia="        ia= key drop
cr ." ian="       ian= key drop
cr ." iang-"      iang- key drop
cr ." iang="      iang= key drop
cr ." iang["      iang[ key drop
cr ." iang]"      iang] key drop
cr ." ian["       ian[ key drop
cr ." ian]"       ian] key drop
cr ." iau-"       iau- key drop
cr ." iau="       iau= key drop
cr ." iau["       iau[ key drop
cr ." iau]"       iau] key drop
cr ." ia["        ia[ key drop
cr ." ia]"        ia] key drop
cr ." ie'"        ie' key drop
cr ." ie-"        ie- key drop
cr ." ie="        ie= key drop
cr ." ie["        ie[ key drop
cr ." ie]"        ie] key drop
cr ." in-"        in- key drop
cr ." in="        in= key drop
cr ." ing'"       ing' key drop
cr ." ing-"       ing- key drop
cr ." ing="       ing= key drop
cr ." ing["       ing[ key drop
cr ." ing]"       ing] key drop
cr ." in["        in[ key drop
cr ." in]"        in] key drop
cr ." io'"        io' key drop
cr ." io-"        io- key drop
cr ." iou-"       iou- key drop
cr ." iou="       iou= key drop
cr ." iou["       iou[ key drop
cr ." iou]"       iou] key drop
cr ." i["         i[ key drop
cr ." i]"         i] key drop
cr ." ja-"        ja- key drop
cr ." ja="        ja= key drop
cr ." jai-"       jai- key drop
cr ." jai="       jai= key drop
cr ." jai["       jai[ key drop
cr ." jai]"       jai] key drop
cr ." jan-"       jan- key drop
cr ." jang-"      jang- key drop
cr ." jang["      jang[ key drop
cr ." jang]"      jang] key drop
cr ." jan["       jan[ key drop
cr ." jan]"       jan] key drop
cr ." jau-"       jau- key drop
cr ." jau="       jau= key drop
cr ." jau["       jau[ key drop
cr ." jau]"       jau] key drop
cr ." ja["        ja[ key drop
cr ." ja]"        ja] key drop
cr ." je'"        je' key drop
cr ." je-"        je- key drop
cr ." je="        je= key drop
cr ." jei]"       jei] key drop
cr ." jen-"       jen- key drop
cr ." jeng'"      jeng' key drop
cr ." jeng-"      jeng- key drop
cr ." jeng["      jeng[ key drop
cr ." jeng]"      jeng] key drop
cr ." jen["       jen[ key drop
cr ." jen]"       jen] key drop
cr ." je["        je[ key drop
cr ." je]"        je] key drop
cr ." ji'"        ji' key drop
cr ." ji-"        ji- key drop
cr ." ji="        ji= key drop
cr ." jia'"       jia' key drop
cr ." jia-"       jia- key drop
cr ." jia="       jia= key drop
cr ." jian'"      jian' key drop
cr ." jian-"      jian- key drop
cr ." jiang-"     jiang- key drop
cr ." jiang["     jiang[ key drop
cr ." jiang]"     jiang] key drop
cr ." jian["      jian[ key drop
cr ." jian]"      jian] key drop
cr ." jiau-"      jiau- key drop
cr ." jiau="      jiau= key drop
cr ." jiau["      jiau[ key drop
cr ." jiau]"      jiau] key drop
cr ." jia["       jia[ key drop
cr ." jia]"       jia] key drop
cr ." jie'"       jie' key drop
cr ." jie-"       jie- key drop
cr ." jie="       jie= key drop
cr ." jie["       jie[ key drop
cr ." jie]"       jie] key drop
cr ." jin-"       jin- key drop
cr ." jing'"      jing' key drop
cr ." jing-"      jing- key drop
cr ." jing["      jing[ key drop
cr ." jing]"      jing] key drop
cr ." jin["       jin[ key drop
cr ." jin]"       jin] key drop
cr ." jiou'"      jiou' key drop
cr ." jiou-"      jiou- key drop
cr ." jiou["      jiou[ key drop
cr ." jiou]"      jiou] key drop
cr ." ji["        ji[ key drop
cr ." ji]"        ji] key drop
cr ." jou-"       jou- key drop
cr ." jou="       jou= key drop
cr ." jou["       jou[ key drop
cr ." jou]"       jou] key drop
cr ." ju-"        ju- key drop
cr ." ju="        ju= key drop
cr ." jua-"       jua- key drop
cr ." juai-"      juai- key drop
cr ." juai["      juai[ key drop
cr ." juai]"      juai] key drop
cr ." juan-"      juan- key drop
cr ." juang-"     juang- key drop
cr ." juang["     juang[ key drop
cr ." juang]"     juang] key drop
cr ." juan["      juan[ key drop
cr ." juan]"      juan] key drop
cr ." jua["       jua[ key drop
cr ." juei-"      juei- key drop
cr ." juei]"      juei] key drop
cr ." jun-"       jun- key drop
cr ." jung-"      jung- key drop
cr ." jung["      jung[ key drop
cr ." jung]"      jung] key drop
cr ." jun["       jun[ key drop
cr ." juo-"       juo- key drop
cr ." juo="       juo= key drop
cr ." ju["        ju[ key drop
cr ." ju]"        ju] key drop
cr ." jy'"        jy' key drop
cr ." jy-"        jy- key drop
cr ." jy="        jy= key drop
cr ." jyu-"       jyu- key drop
cr ." jyu="       jyu= key drop
cr ." jyuan-"     jyuan- key drop
cr ." jyuan["     jyuan[ key drop
cr ." jyuan]"     jyuan] key drop
cr ." jyue-"      jyue- key drop
cr ." jyue="      jyue= key drop
cr ." jyue["      jyue[ key drop
cr ." jyue]"      jyue] key drop
cr ." jyun-"      jyun- key drop
cr ." jyung-"     jyung- key drop
cr ." jyung["     jyung[ key drop
cr ." jyun]"      jyun] key drop
cr ." jyu["       jyu[ key drop
cr ." jyu]"       jyu] key drop
cr ." jy["        jy[ key drop
cr ." jy]"        jy] key drop
cr ." ka-"        ka- key drop
cr ." kai-"       kai- key drop
cr ." kai["       kai[ key drop
cr ." kai]"       kai] key drop
cr ." kan-"       kan- key drop
cr ." kang-"      kang- key drop
cr ." kang="      kang= key drop
cr ." kang]"      kang] key drop
cr ." kan["       kan[ key drop
cr ." kan]"       kan] key drop
cr ." kau-"       kau- key drop
cr ." kau["       kau[ key drop
cr ." kau]"       kau] key drop
cr ." ka["        ka[ key drop
cr ." ke'"        ke' key drop
cr ." ke-"        ke- key drop
cr ." ke="        ke= key drop
cr ." kei-"       kei- key drop
cr ." keng-"      keng- key drop
cr ." ken["       ken[ key drop
cr ." ke["        ke[ key drop
cr ." ke]"        ke] key drop
cr ." kou-"       kou- key drop
cr ." kou["       kou[ key drop
cr ." kou]"       kou] key drop
cr ." ku-"        ku- key drop
cr ." kua-"       kua- key drop
cr ." kuai'"      kuai' key drop
cr ." kuai["      kuai[ key drop
cr ." kuai]"      kuai] key drop
cr ." kuan-"      kuan- key drop
cr ." kuang-"     kuang- key drop
cr ." kuang="     kuang= key drop
cr ." kuang]"     kuang] key drop
cr ." kuan["      kuan[ key drop
cr ." kua["       kua[ key drop
cr ." kua]"       kua] key drop
cr ." kuei-"      kuei- key drop
cr ." kuei="      kuei= key drop
cr ." kuei["      kuei[ key drop
cr ." kuei]"      kuei] key drop
cr ." kuen-"      kuen- key drop
cr ." kuen["      kuen[ key drop
cr ." kuen]"      kuen] key drop
cr ." kung-"      kung- key drop
cr ." kung["      kung[ key drop
cr ." kung]"      kung] key drop
cr ." kuo]"       kuo] key drop
cr ." ku["        ku[ key drop
cr ." ku]"        ku] key drop
cr ." la'"        la' key drop
cr ." la-"        la- key drop
cr ." la="        la= key drop
cr ." lai'"       lai' key drop
cr ." lai="       lai= key drop
cr ." lai]"       lai] key drop
cr ." lan="       lan= key drop
cr ." lang-"      lang- key drop
cr ." lang="      lang= key drop
cr ." lang["      lang[ key drop
cr ." lang]"      lang] key drop
cr ." lan["       lan[ key drop
cr ." lan]"       lan] key drop
cr ." lau'"       lau' key drop
cr ." lau-"       lau- key drop
cr ." lau="       lau= key drop
cr ." lau["       lau[ key drop
cr ." lau]"       lau] key drop
cr ." la["        la[ key drop
cr ." la]"        la] key drop
cr ." le'"        le' key drop
cr ." lei-"       lei- key drop
cr ." lei="       lei= key drop
cr ." lei["       lei[ key drop
cr ." lei]"       lei] key drop
cr ." leng="      leng= key drop
cr ." leng["      leng[ key drop
cr ." leng]"      leng] key drop
cr ." le]"        le] key drop
cr ." li'"        li' key drop
cr ." li-"        li- key drop
cr ." li="        li= key drop
cr ." lian="      lian= key drop
cr ." liang'"     liang' key drop
cr ." liang="     liang= key drop
cr ." liang["     liang[ key drop
cr ." liang]"     liang] key drop
cr ." lian["      lian[ key drop
cr ." lian]"      lian] key drop
cr ." liau-"      liau- key drop
cr ." liau="      liau= key drop
cr ." liau["      liau[ key drop
cr ." liau]"      liau] key drop
cr ." lia["       lia[ key drop
cr ." lie-"       lie- key drop
cr ." lie["       lie[ key drop
cr ." lie]"       lie] key drop
cr ." lin="       lin= key drop
cr ." ling-"      ling- key drop
cr ." ling="      ling= key drop
cr ." ling["      ling[ key drop
cr ." ling]"      ling] key drop
cr ." lin["       lin[ key drop
cr ." lin]"       lin] key drop
cr ." liou-"      liou- key drop
cr ." liou="      liou= key drop
cr ." liou["      liou[ key drop
cr ." liou]"      liou] key drop
cr ." li["        li[ key drop
cr ." li]"        li] key drop
cr ." lo'"        lo' key drop
cr ." lou'"       lou' key drop
cr ." lou-"       lou- key drop
cr ." lou="       lou= key drop
cr ." lou["       lou[ key drop
cr ." lou]"       lou] key drop
cr ." lu'"        lu' key drop
cr ." lu-"        lu- key drop
cr ." lu="        lu= key drop
cr ." luan="      luan= key drop
cr ." luan["      luan[ key drop
cr ." luan]"      luan] key drop
cr ." luen-"      luen- key drop
cr ." luen="      luen= key drop
cr ." luen]"      luen] key drop
cr ." lung'"      lung' key drop
cr ." lung-"      lung- key drop
cr ." lung="      lung= key drop
cr ." lung["      lung[ key drop
cr ." lung]"      lung] key drop
cr ." luo-"       luo- key drop
cr ." luo="       luo= key drop
cr ." luo["       luo[ key drop
cr ." luo]"       luo] key drop
cr ." lu["        lu[ key drop
cr ." lu]"        lu] key drop
cr ." lyu="       lyu= key drop
cr ." lyue]"      lyue] key drop
cr ." lyu["       lyu[ key drop
cr ." lyu]"       lyu] key drop
cr ." ma'"        ma' key drop
cr ." ma-"        ma- key drop
cr ." ma="        ma= key drop
cr ." mai'"       mai' key drop
cr ." mai="       mai= key drop
cr ." mai["       mai[ key drop
cr ." mai]"       mai] key drop
cr ." man-"       man- key drop
cr ." man="       man= key drop
cr ." mang="      mang= key drop
cr ." mang["      mang[ key drop
cr ." man["       man[ key drop
cr ." man]"       man] key drop
cr ." mau'"       mau' key drop
cr ." mau-"       mau- key drop
cr ." mau="       mau= key drop
cr ." mau["       mau[ key drop
cr ." mau]"       mau] key drop
cr ." ma["        ma[ key drop
cr ." ma]"        ma] key drop
cr ." me'"        me' key drop
cr ." me="        me= key drop
cr ." mei'"       mei' key drop
cr ." mei="       mei= key drop
cr ." mei["       mei[ key drop
cr ." mei]"       mei] key drop
cr ." men'"       men' key drop
cr ." men-"       men- key drop
cr ." men="       men= key drop
cr ." meng-"      meng- key drop
cr ." meng="      meng= key drop
cr ." meng["      meng[ key drop
cr ." meng]"      meng] key drop
cr ." men]"       men] key drop
cr ." me]"        me] key drop
cr ." mi-"        mi- key drop
cr ." mi="        mi= key drop
cr ." mian'"      mian' key drop
cr ." mian="      mian= key drop
cr ." mian["      mian[ key drop
cr ." mian]"      mian] key drop
cr ." miau-"      miau- key drop
cr ." miau="      miau= key drop
cr ." miau["      miau[ key drop
cr ." miau]"      miau] key drop
cr ." mie-"       mie- key drop
cr ." mie]"       mie] key drop
cr ." min="       min= key drop
cr ." ming'"      ming' key drop
cr ." ming="      ming= key drop
cr ." ming["      ming[ key drop
cr ." ming]"      ming] key drop
cr ." min["       min[ key drop
cr ." miou]"      miou] key drop
cr ." mi["        mi[ key drop
cr ." mi]"        mi] key drop
cr ." mo'"        mo' key drop
cr ." mo-"        mo- key drop
cr ." mo="        mo= key drop
cr ." mou-"       mou- key drop
cr ." mou="       mou= key drop
cr ." mou["       mou[ key drop
cr ." mo["        mo[ key drop
cr ." mo]"        mo] key drop
cr ." mu="        mu= key drop
cr ." mu["        mu[ key drop
cr ." mu]"        mu] key drop
cr ." na'"        na' key drop
cr ." na-"        na- key drop
cr ." na="        na= key drop
cr ." nai'"       nai' key drop
cr ." nai["       nai[ key drop
cr ." nai]"       nai] key drop
cr ." nan'"       nan' key drop
cr ." nan-"       nan- key drop
cr ." nan="       nan= key drop
cr ." nang-"      nang- key drop
cr ." nang="      nang= key drop
cr ." nang["      nang[ key drop
cr ." nang]"      nang] key drop
cr ." nan["       nan[ key drop
cr ." nan]"       nan] key drop
cr ." nau'"       nau' key drop
cr ." nau-"       nau- key drop
cr ." nau="       nau= key drop
cr ." nau["       nau[ key drop
cr ." nau]"       nau] key drop
cr ." na["        na[ key drop
cr ." na]"        na] key drop
cr ." ne'"        ne' key drop
cr ." nei["       nei[ key drop
cr ." nei]"       nei] key drop
cr ." neng="      neng= key drop
cr ." nen]"       nen] key drop
cr ." ne]"        ne] key drop
cr ." ni-"        ni- key drop
cr ." ni="        ni= key drop
cr ." nian-"      nian- key drop
cr ." nian="      nian= key drop
cr ." niang'"     niang' key drop
cr ." niang="     niang= key drop
cr ." niang]"     niang] key drop
cr ." nian["      nian[ key drop
cr ." nian]"      nian] key drop
cr ." niau["      niau[ key drop
cr ." niau]"      niau] key drop
cr ." nie-"       nie- key drop
cr ." nie="       nie= key drop
cr ." nie]"       nie] key drop
cr ." nin="       nin= key drop
cr ." ning="      ning= key drop
cr ." ning["      ning[ key drop
cr ." ning]"      ning] key drop
cr ." niou-"      niou- key drop
cr ." niou="      niou= key drop
cr ." niou["      niou[ key drop
cr ." niou]"      niou] key drop
cr ." ni["        ni[ key drop
cr ." ni]"        ni] key drop
cr ." nou]"       nou] key drop
cr ." nu="        nu= key drop
cr ." nuan["      nuan[ key drop
cr ." nung="      nung= key drop
cr ." nung]"      nung] key drop
cr ." nuo="       nuo= key drop
cr ." nuo]"       nuo] key drop
cr ." nu["        nu[ key drop
cr ." nu]"        nu] key drop
cr ." nyue]"      nyue] key drop
cr ." nyu["       nyu[ key drop
cr ." nyu]"       nyu] key drop
cr ." o-"         o- key drop
cr ." cr ." o="         o= key drop
cr ." ou-"        ou- key drop
cr ." ou["        ou[ key drop
cr ." ou]"        ou] key drop
cr ." o["         o[ key drop
cr ." o]"         o] key drop
cr ." pa-"        pa- key drop
cr ." pa="        pa= key drop
cr ." pai-"       pai- key drop
cr ." pai="       pai= key drop
cr ." pai["       pai[ key drop
cr ." pai]"       pai] key drop
cr ." pan-"       pan- key drop
cr ." pan="       pan= key drop
cr ." pang-"      pang- key drop
cr ." pang="      pang= key drop
cr ." pang["      pang[ key drop
cr ." pang]"      pang] key drop
cr ." pan]"       pan] key drop
cr ." pau-"       pau- key drop
cr ." pau="       pau= key drop
cr ." pau["       pau[ key drop
cr ." pau]"       pau] key drop
cr ." pa]"        pa] key drop
cr ." pei-"       pei- key drop
cr ." pei="       pei= key drop
cr ." pei]"       pei] key drop
cr ." pen-"       pen- key drop
cr ." pen="       pen= key drop
cr ." peng-"      peng- key drop
cr ." peng="      peng= key drop
cr ." peng["      peng[ key drop
cr ." peng]"      peng] key drop
cr ." pen]"       pen] key drop
cr ." pi-"        pi- key drop
cr ." pi="        pi= key drop
cr ." pian-"      pian- key drop
cr ." pian="      pian= key drop
cr ." pian["      pian[ key drop
cr ." pian]"      pian] key drop
cr ." piau-"      piau- key drop
cr ." piau="      piau= key drop
cr ." piau["      piau[ key drop
cr ." piau]"      piau] key drop
cr ." pie-"       pie- key drop
cr ." pie["       pie[ key drop
cr ." pin-"       pin- key drop
cr ." pin="       pin= key drop
cr ." ping-"      ping- key drop
cr ." ping="      ping= key drop
cr ." pin["       pin[ key drop
cr ." pin]"       pin] key drop
cr ." pi["        pi[ key drop
cr ." pi]"        pi] key drop
cr ." po'"        po' key drop
cr ." po-"        po- key drop
cr ." po="        po= key drop
cr ." pou-"       pou- key drop
cr ." pou="       pou= key drop
cr ." pou["       pou[ key drop
cr ." po["        po[ key drop
cr ." po]"        po] key drop
cr ." pu-"        pu- key drop
cr ." pu="        pu= key drop
cr ." pu["        pu[ key drop
cr ." pu]"        pu] key drop
cr ." ran="       ran= key drop
cr ." rang-"      rang- key drop
cr ." rang="      rang= key drop
cr ." rang["      rang[ key drop
cr ." rang]"      rang] key drop
cr ." ran["       ran[ key drop
cr ." rau="       rau= key drop
cr ." rau["       rau[ key drop
cr ." rau]"       rau] key drop
cr ." ren'"       ren' key drop
cr ." ren="       ren= key drop
cr ." reng-"      reng- key drop
cr ." reng="      reng= key drop
cr ." ren["       ren[ key drop
cr ." ren]"       ren] key drop
cr ." re["        re[ key drop
cr ." re]"        re] key drop
cr ." rou="       rou= key drop
cr ." rou]"       rou] key drop
cr ." ru="        ru= key drop
cr ." ruan["      ruan[ key drop
cr ." ruei["      ruei[ key drop
cr ." ruei]"      ruei] key drop
cr ." rung="      rung= key drop
cr ." rung["      rung[ key drop
cr ." run]"       run] key drop
cr ." ruo]"       ruo] key drop
cr ." ru["        ru[ key drop
cr ." ru]"        ru] key drop
cr ." ry]"        ry] key drop
cr ." sha-"       sha- key drop
cr ." shai-"      shai- key drop
cr ." shai["      shai[ key drop
cr ." shai]"      shai] key drop
cr ." shan-"      shan- key drop
cr ." shang'"     shang' key drop
cr ." shang-"     shang- key drop
cr ." shang["     shang[ key drop
cr ." shang]"     shang] key drop
cr ." shan["      shan[ key drop
cr ." shan]"      shan] key drop
cr ." shau'"      shau' key drop
cr ." shau-"      shau- key drop
cr ." shau="      shau= key drop
cr ." shau["      shau[ key drop
cr ." shau]"      shau] key drop
cr ." sha["       sha[ key drop
cr ." sha]"       sha] key drop
cr ." she-"       she- key drop
cr ." she="       she= key drop
cr ." shei="      shei= key drop
cr ." shen'"      shen' key drop
cr ." shen-"      shen- key drop
cr ." shen="      shen= key drop
cr ." sheng'"     sheng' key drop
cr ." sheng-"     sheng- key drop
cr ." sheng="     sheng= key drop
cr ." sheng["     sheng[ key drop
cr ." sheng]"     sheng] key drop
cr ." shen["      shen[ key drop
cr ." shen]"      shen] key drop
cr ." she["       she[ key drop
cr ." she]"       she] key drop
cr ." shi'"       shi' key drop
cr ." shi-"       shi- key drop
cr ." shi="       shi= key drop
cr ." shia'"      shia' key drop
cr ." shia-"      shia- key drop
cr ." shia="      shia= key drop
cr ." shian-"     shian- key drop
cr ." shian="     shian= key drop
cr ." shiang-"    shiang- key drop
cr ." shiang="    shiang= key drop
cr ." shiang["    shiang[ key drop
cr ." shiang]"    shiang] key drop
cr ." shian["     shian[ key drop
cr ." shian]"     shian] key drop
cr ." shiau-"     shiau- key drop
cr ." shiau="     shiau= key drop
cr ." shiau["     shiau[ key drop
cr ." shiau]"     shiau] key drop
cr ." shia]"      shia] key drop
cr ." shie'"      shie' key drop
cr ." shie-"      shie- key drop
cr ." shie="      shie= key drop
cr ." shie["      shie[ key drop
cr ." shie]"      shie] key drop
cr ." shin-"      shin- key drop
cr ." shin="      shin= key drop
cr ." shing'"     shing' key drop
cr ." shing-"     shing- key drop
cr ." shing="     shing= key drop
cr ." shing["     shing[ key drop
cr ." shing]"     shing] key drop
cr ." shin]"      shin] key drop
cr ." shiou-"     shiou- key drop
cr ." shiou["     shiou[ key drop
cr ." shiou]"     shiou] key drop
cr ." shi["       shi[ key drop
cr ." shi]"       shi] key drop
cr ." shou-"      shou- key drop
cr ." shou["      shou[ key drop
cr ." shou]"      shou] key drop
cr ." shu'"       shu' key drop
cr ." shu-"       shu- key drop
cr ." shu="       shu= key drop
cr ." shua-"      shua- key drop
cr ." shuai-"     shuai- key drop
cr ." shuai["     shuai[ key drop
cr ." shuai]"     shuai] key drop
cr ." shuan-"     shuan- key drop
cr ." shuang-"    shuang- key drop
cr ." shuang["    shuang[ key drop
cr ." shuan]"     shuan] key drop
cr ." shua["      shua[ key drop
cr ." shua]"      shua] key drop
cr ." shuei="     shuei= key drop
cr ." shuei["     shuei[ key drop
cr ." shuei]"     shuei] key drop
cr ." shun["      shun[ key drop
cr ." shun]"      shun] key drop
cr ." shuo-"      shuo- key drop
cr ." shuo]"      shuo] key drop
cr ." shu["       shu[ key drop
cr ." shu]"       shu] key drop
cr ." shy'"       shy' key drop
cr ." shy-"       shy- key drop
cr ." shy="       shy= key drop
cr ." shyu'"      shyu' key drop
cr ." shyu-"      shyu- key drop
cr ." shyu="      shyu= key drop
cr ." shyuan-"    shyuan- key drop
cr ." shyuan="    shyuan= key drop
cr ." shyuan["    shyuan[ key drop
cr ." shyuan]"    shyuan] key drop
cr ." shyue-"     shyue- key drop
cr ." shyue="     shyue= key drop
cr ." shyue["     shyue[ key drop
cr ." shyue]"     shyue] key drop
cr ." shyun-"     shyun- key drop
cr ." shyun="     shyun= key drop
cr ." shyung'"    shyung' key drop
cr ." shyung-"    shyung- key drop
cr ." shyung="    shyung= key drop
cr ." shyun]"     shyun] key drop
cr ." shyu["      shyu[ key drop
cr ." shyu]"      shyu] key drop
cr ." shy["       shy[ key drop
cr ." shy]"       shy] key drop
cr ." ta-"        ta- key drop
cr ." tai'"       tai' key drop
cr ." tai-"       tai- key drop
cr ." tai="       tai= key drop
cr ." tai]"       tai] key drop
cr ." tan-"       tan- key drop
cr ." tan="       tan= key drop
cr ." tang-"      tang- key drop
cr ." tang="      tang= key drop
cr ." tang["      tang[ key drop
cr ." tang]"      tang] key drop
cr ." tan["       tan[ key drop
cr ." tan]"       tan] key drop
cr ." tau'"       tau' key drop
cr ." tau-"       tau- key drop
cr ." tau="       tau= key drop
cr ." tau["       tau[ key drop
cr ." tau]"       tau] key drop
cr ." ta["        ta[ key drop
cr ." ta]"        ta] key drop
cr ." tei-"       tei- key drop
cr ." teng-"      teng- key drop
cr ." teng="      teng= key drop
cr ." te]"        te] key drop
cr ." ti-"        ti- key drop
cr ." ti="        ti= key drop
cr ." tian'"      tian' key drop
cr ." tian-"      tian- key drop
cr ." tian="      tian= key drop
cr ." tian["      tian[ key drop
cr ." tiau-"      tiau- key drop
cr ." tiau="      tiau= key drop
cr ." tiau["      tiau[ key drop
cr ." tiau]"      tiau] key drop
cr ." tie-"       tie- key drop
cr ." tie["       tie[ key drop
cr ." tie]"       tie] key drop
cr ." ting-"      ting- key drop
cr ." ting="      ting= key drop
cr ." ting["      ting[ key drop
cr ." ti["        ti[ key drop
cr ." ti]"        ti] key drop
cr ." tou'"       tou' key drop
cr ." tou-"       tou- key drop
cr ." tou="       tou= key drop
cr ." tou]"       tou] key drop
cr ." tsa-"       tsa- key drop
cr ." tsai-"      tsai- key drop
cr ." tsai="      tsai= key drop
cr ." tsai["      tsai[ key drop
cr ." tsai]"      tsai] key drop
cr ." tsan-"      tsan- key drop
cr ." tsan="      tsan= key drop
cr ." tsang-"     tsang- key drop
cr ." tsang="     tsang= key drop
cr ." tsan["      tsan[ key drop
cr ." tsan]"      tsan] key drop
cr ." tsau-"      tsau- key drop
cr ." tsau="      tsau= key drop
cr ." tsau["      tsau[ key drop
cr ." tsa["       tsa[ key drop
cr ." tsen-"      tsen- key drop
cr ." tsen="      tsen= key drop
cr ." tseng-"     tseng- key drop
cr ." tseng="     tseng= key drop
cr ." tse]"       tse] key drop
cr ." tsu-"       tsu- key drop
cr ." tsuan-"     tsuan- key drop
cr ." tsuan="     tsuan= key drop
cr ." tsuan]"     tsuan] key drop
cr ." tsuei-"     tsuei- key drop
cr ." tsuei["     tsuei[ key drop
cr ." tsuei]"     tsuei] key drop
cr ." tsuen-"     tsuen- key drop
cr ." tsuen="     tsuen= key drop
cr ." tsuen["     tsuen[ key drop
cr ." tsuen]"     tsuen] key drop
cr ." tsung-"     tsung- key drop
cr ." tsung="     tsung= key drop
cr ." tsung]"     tsung] key drop
cr ." tsuo-"      tsuo- key drop
cr ." tsuo="      tsuo= key drop
cr ." tsuo]"      tsuo] key drop
cr ." tsu]"       tsu] key drop
cr ." tsy'"       tsy' key drop
cr ." tsy-"       tsy- key drop
cr ." tsy="       tsy= key drop
cr ." tsy["       tsy[ key drop
cr ." tsy]"       tsy] key drop
cr ." tu'"        tu' key drop
cr ." tu-"        tu- key drop
cr ." tu="        tu= key drop
cr ." tuan-"      tuan- key drop
cr ." tuan="      tuan= key drop
cr ." tuei-"      tuei- key drop
cr ." tuei="      tuei= key drop
cr ." tuei["      tuei[ key drop
cr ." tuei]"      tuei] key drop
cr ." tun-"       tun- key drop
cr ." tun="       tun= key drop
cr ." tung'"      tung' key drop
cr ." tung-"      tung- key drop
cr ." tung="      tung= key drop
cr ." tung["      tung[ key drop
cr ." tung]"      tung] key drop
cr ." tun["       tun[ key drop
cr ." tun]"       tun] key drop
cr ." tuo'"       tuo' key drop
cr ." tuo-"       tuo- key drop
cr ." tuo="       tuo= key drop
cr ." tuo["       tuo[ key drop
cr ." tuo]"       tuo] key drop
cr ." tu["        tu[ key drop
cr ." tu]"        tu] key drop
cr ." u'"         u' key drop
cr ." u-"         u- key drop
cr ." u="         u= key drop
cr ." ua'"        ua' key drop
cr ." ua-"        ua- key drop
cr ." ua="        ua= key drop
cr ." uai'"       uai' key drop
cr ." uai-"       uai- key drop
cr ." uai["       uai[ key drop
cr ." uai]"       uai] key drop
cr ." uan-"       uan- key drop
cr ." uan="       uan= key drop
cr ." uang'"      uang' key drop
cr ." uang-"      uang- key drop
cr ." uang="      uang= key drop
cr ." uang["      uang[ key drop
cr ." uang]"      uang] key drop
cr ." uan["       uan[ key drop
cr ." uan]"       uan] key drop
cr ." ua["        ua[ key drop
cr ." ua]"        ua] key drop
cr ." uei'"       uei' key drop
cr ." uei-"       uei- key drop
cr ." uei="       uei= key drop
cr ." uei["       uei[ key drop
cr ." uei]"       uei] key drop
cr ." uen'"       uen' key drop
cr ." uen-"       uen- key drop
cr ." uen="       uen= key drop
cr ." uen["       uen[ key drop
cr ." uen]"       uen] key drop
cr ." ung-"       ung- key drop
cr ." ung["       ung[ key drop
cr ." ung]"       ung] key drop
cr ." uo-"        uo- key drop
cr ." uo["        uo[ key drop
cr ." uo]"        uo] key drop
cr ." u["         u[ key drop
cr ." u]"         u] key drop
cr ." xa-"        xa- key drop
cr ." xai-"       xai- key drop
cr ." xai]"       xai] key drop
cr ." xan-"       xan- key drop
cr ." xang-"      xang- key drop
cr ." xang["      xang[ key drop
cr ." xang]"      xang] key drop
cr ." xan["       xan[ key drop
cr ." xan]"       xan] key drop
cr ." xau-"       xau- key drop
cr ." xau["       xau[ key drop
cr ." xau]"       xau] key drop
cr ." xa["        xa[ key drop
cr ." xa]"        xa] key drop
cr ." xen-"       xen- key drop
cr ." xeng-"      xeng- key drop
cr ." xe]"        xe] key drop
cr ." xou'"       xou' key drop
cr ." xou-"       xou- key drop
cr ." xou["       xou[ key drop
cr ." xou]"       xou] key drop
cr ." xu'"        xu' key drop
cr ." xu-"        xu- key drop
cr ." xu="        xu= key drop
cr ." xuan-"      xuan- key drop
cr ." xuan]"      xuan] key drop
cr ." xuei-"      xuei- key drop
cr ." xuei="      xuei= key drop
cr ." xuei["      xuei[ key drop
cr ." xuei]"      xuei] key drop
cr ." xun-"       xun- key drop
cr ." xung-"      xung- key drop
cr ." xung["      xung[ key drop
cr ." xung]"      xung] key drop
cr ." xun["       xun[ key drop
cr ." xuo'"       xuo' key drop
cr ." xuo-"       xuo- key drop
cr ." xuo["       xuo[ key drop
cr ." xu]"        xu] key drop
cr ." xy'"        xy' key drop
cr ." xy-"        xy- key drop
cr ." xy["        xy[ key drop
cr ." xy]"        xy] key drop
cr ." you0"       you0 key drop
cr ." yu'"        yu' key drop
cr ." yu-"        yu- key drop
cr ." yu="        yu= key drop
cr ." yuan-"      yuan- key drop
cr ." yuan="      yuan= key drop
cr ." yuan["      yuan[ key drop
cr ." yuan]"      yuan] key drop
cr ." yue-"       yue- key drop
cr ." yue]"       yue] key drop
cr ." yun-"       yun- key drop
cr ." yun="       yun= key drop
cr ." yung-"      yung- key drop
cr ." yung="      yung= key drop
cr ." yung["      yung[ key drop
cr ." yung]"      yung] key drop
cr ." yun["       yun[ key drop
cr ." yun]"       yun] key drop
cr ." yu["        yu[ key drop
cr ." yu]"        yu] key drop
cr ." za-"        za- key drop
cr ." za="        za= key drop
cr ." zai'"       zai' key drop
cr ." zai-"       zai- key drop
cr ." zai["       zai[ key drop
cr ." zai]"       zai] key drop
cr ." zan'"       zan' key drop
cr ." zan-"       zan- key drop
cr ." zan="       zan= key drop
cr ." zang-"      zang- key drop
cr ." zang["      zang[ key drop
cr ." zang]"      zang] key drop
cr ." zan["       zan[ key drop
cr ." zan]"       zan] key drop
cr ." zau-"       zau- key drop
cr ." zau="       zau= key drop
cr ." zau["       zau[ key drop
cr ." zau]"       zau] key drop
cr ." za["        za[ key drop
cr ." ze="        ze= key drop
cr ." zei="       zei= key drop
cr ." zeng-"      zeng- key drop
cr ." zeng]"      zeng] key drop
cr ." zen["       zen[ key drop
cr ." zen]"       zen] key drop
cr ." ze]"        ze] key drop
cr ." zou-"       zou- key drop
cr ." zou["       zou[ key drop
cr ." zou]"       zou] key drop
cr ." zu-"        zu- key drop
cr ." zu="        zu= key drop
cr ." zuan-"      zuan- key drop
cr ." zuan["      zuan[ key drop
cr ." zuan]"      zuan] key drop
cr ." zui["       zui[ key drop
cr ." zui]"       zui] key drop
cr ." zun-"       zun- key drop
cr ." zung-"      zung- key drop
cr ." zung["      zung[ key drop
cr ." zung]"      zung] key drop
cr ." zun["       zun[ key drop
cr ." zuo-"       zuo- key drop
cr ." zuo="       zuo= key drop
cr ." zuo["       zuo[ key drop
cr ." zuo]"       zuo] key drop
cr ." zu["        zu[ key drop
cr ." zy'"        zy' key drop
cr ." zy-"        zy- key drop
cr ." zy["        zy[ key drop
cr ." zy]"        zy] key drop

