cls

cr s" a-"         type a- key drop
cr s" a="         type a= key drop
cr s" ai-"        type ai- key drop
cr s" ai="        type ai= key drop
cr s" ai["        type ai[ key drop
cr s" ai]"        type ai] key drop
cr s" an-"        type an- key drop
cr s" ang-"       type ang- key drop
cr s" ang="       type ang= key drop
cr s" ang]"       type ang] key drop
cr s" an["        type an[ key drop
cr s" an]"        type an] key drop
cr s" au-"        type au- key drop
cr s" au="        type au= key drop
cr s" au["        type au[ key drop
cr s" au]"        type au] key drop
cr s" a["         type a[ key drop
cr s" a]"         type a] key drop
cr s" ba'"        type ba' key drop
cr s" ba-"        type ba- key drop
cr s" ba="        type ba= key drop
cr s" bai'"       type bai' key drop
cr s" bai-"       type bai- key drop
cr s" bai="       type bai= key drop
cr s" bai["       type bai[ key drop
cr s" bai]"       type bai] key drop
cr s" ban-"       type ban- key drop
cr s" bang-1"     type bang-1 key drop
cr s" bang["      type bang[ key drop
cr s" bang]"      type bang] key drop
cr s" ban["       type ban[ key drop
cr s" ban]"       type ban] key drop
cr s" bau-"       type bau- key drop
cr s" bau="       type bau= key drop
cr s" bau["       type bau[ key drop
cr s" bau]"       type bau] key drop
cr s" ba["        type ba[ key drop
cr s" ba]"        type ba] key drop
cr s" bei'"       type bei' key drop
cr s" bei-"       type bei- key drop
cr s" bei["       type bei[ key drop
cr s" bei]"       type bei] key drop
cr s" ben'"       type ben' key drop
cr s" ben-"       type ben- key drop
cr s" beng-"      type beng- key drop
cr s" beng="      type beng= key drop
cr s" beng["      type beng[ key drop
cr s" beng]"      type beng] key drop
cr s" ben["       type ben[ key drop
cr s" ben]"       type ben] key drop
cr s" bi-"        type bi- key drop
cr s" bi="        type bi= key drop
cr s" bian'"      type bian' key drop
cr s" bian-"      type bian- key drop
cr s" bian["      type bian[ key drop
cr s" bian]"      type bian] key drop
cr s" biau-"      type biau- key drop
cr s" biau["      type biau[ key drop
cr s" biau]"      type biau] key drop
cr s" bie-"       type bie- key drop
cr s" bie="       type bie= key drop
cr s" bie["       type bie[ key drop
cr s" bie]"       type bie] key drop
cr s" bin-"       type bin- key drop
cr s" bing-"      type bing- key drop
cr s" bing["      type bing[ key drop
cr s" bing]"      type bing] key drop
cr s" bin]"       type bin] key drop
cr s" bi["        type bi[ key drop
cr s" bi]"        type bi] key drop
cr s" bo'"        type bo' key drop
cr s" bo-"        type bo- key drop
cr s" bo="        type bo= key drop
cr s" bo["        type bo[ key drop
cr s" bo]"        type bo] key drop
cr s" bu'"        type bu' key drop
cr s" bu-"        type bu- key drop
cr s" bu="        type bu= key drop
cr s" bu["        type bu[ key drop
cr s" bu]"        type bu] key drop
cr s" cha-"       type cha- key drop
cr s" cha="       type cha= key drop
cr s" chai-"      type chai- key drop
cr s" chai="      type chai= key drop
cr s" chai["      type chai[ key drop
cr s" chai]"      type chai] key drop
cr s" chan-"      type chan- key drop
cr s" chan="      type chan= key drop
cr s" chang-"     type chang- key drop
cr s" chang="     type chang= key drop
cr s" chang["     type chang[ key drop
cr s" chang]"     type chang] key drop
cr s" chan["      type chan[ key drop
cr s" chan]"      type chan] key drop
cr s" chau-"      type chau- key drop
cr s" chau="      type chau= key drop
cr s" chau["      type chau[ key drop
cr s" chau]"      type chau] key drop
cr s" cha["       type cha[ key drop
cr s" cha]"       type cha] key drop
cr s" che-"       type che- key drop
cr s" chen'"      type chen' key drop
cr s" chen-"      type chen- key drop
cr s" chen="      type chen= key drop
cr s" cheng-"     type cheng- key drop
cr s" cheng="     type cheng= key drop
cr s" cheng["     type cheng[ key drop
cr s" cheng]"     type cheng] key drop
cr s" chen]"      type chen] key drop
cr s" che["       type che[ key drop
cr s" che]"       type che] key drop
cr s" chi'"       type chi' key drop
cr s" chi-"       type chi- key drop
cr s" chi="       type chi= key drop
cr s" chia-"      type chia- key drop
cr s" chian'"     type chian' key drop
cr s" chian-"     type chian- key drop
cr s" chian="     type chian= key drop
cr s" chiang-"    type chiang- key drop
cr s" chiang="    type chiang= key drop
cr s" chiang["    type chiang[ key drop
cr s" chiang]"    type chiang] key drop
cr s" chian["     type chian[ key drop
cr s" chian]"     type chian] key drop
cr s" chiau-"     type chiau- key drop
cr s" chiau="     type chiau= key drop
cr s" chiau["     type chiau[ key drop
cr s" chiau]"     type chiau] key drop
cr s" chia["      type chia[ key drop
cr s" chia]"      type chia] key drop
cr s" chie-"      type chie- key drop
cr s" chie="      type chie= key drop
cr s" chie["      type chie[ key drop
cr s" chie]"      type chie] key drop
cr s" chin'"      type chin' key drop
cr s" chin-"      type chin- key drop
cr s" chin="      type chin= key drop
cr s" ching'"     type ching' key drop
cr s" ching-"     type ching- key drop
cr s" ching="     type ching= key drop
cr s" ching["     type ching[ key drop
cr s" ching]"     type ching] key drop
cr s" chin["      type chin[ key drop
cr s" chin]"      type chin] key drop
cr s" chiou-"     type chiou- key drop
cr s" chiou="     type chiou= key drop
cr s" chi["       type chi[ key drop
cr s" chi]"       type chi] key drop
cr s" chou'"      type chou' key drop
cr s" chou-"      type chou- key drop
cr s" chou="      type chou= key drop
cr s" chou["      type chou[ key drop
cr s" chou]"      type chou] key drop
cr s" chu'"       type chu' key drop
cr s" chu-"       type chu- key drop
cr s" chu="       type chu= key drop
cr s" chua-"      type chua- key drop
cr s" chuai-"     type chuai- key drop
cr s" chuai["     type chuai[ key drop
cr s" chuai]"     type chuai] key drop
cr s" chuan-"     type chuan- key drop
cr s" chuan="     type chuan= key drop
cr s" chuang-"    type chuang- key drop
cr s" chuang="    type chuang= key drop
cr s" chuang["    type chuang[ key drop
cr s" chuang]"    type chuang] key drop
cr s" chuan["     type chuan[ key drop
cr s" chuan]"     type chuan] key drop
cr s" chui-"      type chui- key drop
cr s" chui="      type chui= key drop
cr s" chun-"      type chun- key drop
cr s" chun="      type chun= key drop
cr s" chung-"     type chung- key drop
cr s" chung="     type chung= key drop
cr s" chung["     type chung[ key drop
cr s" chung]"     type chung] key drop
cr s" chun["      type chun[ key drop
cr s" chuo-"      type chuo- key drop
cr s" chuo]"      type chuo] key drop
cr s" chu["       type chu[ key drop
cr s" chu]"       type chu] key drop
cr s" chy-"       type chy- key drop
cr s" chy="       type chy= key drop
cr s" chyu'"      type chyu' key drop
cr s" chyu-"      type chyu- key drop
cr s" chyu="      type chyu= key drop
cr s" chyuan-"    type chyuan- key drop
cr s" chyuan="    type chyuan= key drop
cr s" chyuan["    type chyuan[ key drop
cr s" chyuan]"    type chyuan] key drop
cr s" chyue-"     type chyue- key drop
cr s" chyue="     type chyue= key drop
cr s" chyue]"     type chyue] key drop
cr s" chyun-"     type chyun- key drop
cr s" chyun="     type chyun= key drop
cr s" chyung="    type chyung= key drop
cr s" chyu["      type chyu[ key drop
cr s" chyu]"      type chyu] key drop
cr s" chy["       type chy[ key drop
cr s" chy]"       type chy] key drop
cr s" da'"        type da' key drop
cr s" da-"        type da- key drop
cr s" da="        type da= key drop
cr s" dai'"       type dai' key drop
cr s" dai-"       type dai- key drop
cr s" dai["       type dai[ key drop
cr s" dai]"       type dai] key drop
cr s" dan-"       type dan- key drop
cr s" dang-"      type dang- key drop
cr s" dang["      type dang[ key drop
cr s" dang]"      type dang] key drop
cr s" dan["       type dan[ key drop
cr s" dan]"       type dan] key drop
cr s" dau'"       type dau' key drop
cr s" dau-"       type dau- key drop
cr s" dau["       type dau[ key drop
cr s" dau]"       type dau] key drop
cr s" da["        type da[ key drop
cr s" da]"        type da] key drop
cr s" de'"        type de' key drop
cr s" de="        type de= key drop
cr s" dei["       type dei[ key drop
cr s" deng-"      type deng- key drop
cr s" deng["      type deng[ key drop
cr s" deng]"      type deng] key drop
cr s" den]"       type den] key drop
cr s" di'"        type di' key drop
cr s" di-"        type di- key drop
cr s" di="        type di= key drop
cr s" dian'"      type dian' key drop
cr s" dian-"      type dian- key drop
cr s" dian["      type dian[ key drop
cr s" dian]"      type dian] key drop
cr s" diau'"      type diau' key drop
cr s" diau-"      type diau- key drop
cr s" diau]"      type diau] key drop
cr s" die-"       type die- key drop
cr s" die="       type die= key drop
cr s" ding-"      type ding- key drop
cr s" ding["      type ding[ key drop
cr s" ding]"      type ding] key drop
cr s" diou-"      type diou- key drop
cr s" di["        type di[ key drop
cr s" di]"        type di] key drop
cr s" dou-"       type dou- key drop
cr s" dou["       type dou[ key drop
cr s" dou]"       type dou] key drop
cr s" du'"        type du' key drop
cr s" du-"        type du- key drop
cr s" du="        type du= key drop
cr s" duan-"      type duan- key drop
cr s" duan["      type duan[ key drop
cr s" duan]"      type duan] key drop
cr s" duei-"      type duei- key drop
cr s" duei]"      type duei] key drop
cr s" dun-"       type dun- key drop
cr s" dung-"      type dung- key drop
cr s" dung["      type dung[ key drop
cr s" dung]"      type dung] key drop
cr s" dun["       type dun[ key drop
cr s" dun]"       type dun] key drop
cr s" duo'"       type duo' key drop
cr s" duo-"       type duo- key drop
cr s" duo="       type duo= key drop
cr s" duo["       type duo[ key drop
cr s" duo]"       type duo] key drop
cr s" du["        type du[ key drop
cr s" du]"        type du] key drop
cr s" e-"         type e- key drop
cr s" e="         type e= key drop
cr s" ei="        type ei= key drop
cr s" ei["        type ei[ key drop
cr s" ei]"        type ei] key drop
cr s" en-"        type en- key drop
cr s" eng'"       type eng' key drop
cr s" eng="       type eng= key drop
cr s" eng["       type eng[ key drop
cr s" eng]"       type eng] key drop
cr s" en]"        type en] key drop
cr s" er="        type er= key drop
cr s" er["        type er[ key drop
cr s" er]"        type er] key drop
cr s" e["         type e[ key drop
cr s" e]"         type e] key drop
cr s" fa'"        type fa' key drop
cr s" fa-"        type fa- key drop
cr s" fa="        type fa= key drop
cr s" fan'"       type fan' key drop
cr s" fan-"       type fan- key drop
cr s" fan="       type fan= key drop
cr s" fang'"      type fang' key drop
cr s" fang-"      type fang- key drop
cr s" fang="      type fang= key drop
cr s" fang["      type fang[ key drop
cr s" fang]"      type fang] key drop
cr s" fan["       type fan[ key drop
cr s" fan]"       type fan] key drop
cr s" fa["        type fa[ key drop
cr s" fa]"        type fa] key drop
cr s" fei-"       type fei- key drop
cr s" fei="       type fei= key drop
cr s" fei["       type fei[ key drop
cr s" fei]"       type fei] key drop
cr s" fen'"       type fen' key drop
cr s" fen-"       type fen- key drop
cr s" fen="       type fen= key drop
cr s" feng-"      type feng- key drop
cr s" feng="      type feng= key drop
cr s" feng["      type feng[ key drop
cr s" feng]"      type feng] key drop
cr s" fen["       type fen[ key drop
cr s" fen]"       type fen] key drop
cr s" fo="        type fo= key drop
cr s" fou["       type fou[ key drop
cr s" fu'"        type fu' key drop
cr s" fu-"        type fu- key drop
cr s" fu="        type fu= key drop
cr s" fu["        type fu[ key drop
cr s" fu]"        type fu] key drop
cr s" ga-"        type ga- key drop
cr s" ga="        type ga= key drop
cr s" gai-"       type gai- key drop
cr s" gai["       type gai[ key drop
cr s" gai]"       type gai] key drop
cr s" gan-"       type gan- key drop
cr s" gang'"      type gang' key drop
cr s" gang-"      type gang- key drop
cr s" gang["      type gang[ key drop
cr s" gang]"      type gang] key drop
cr s" gan["       type gan[ key drop
cr s" gan]"       type gan] key drop
cr s" gau-"       type gau- key drop
cr s" gau["       type gau[ key drop
cr s" gau]"       type gau] key drop
cr s" ga]"        type ga] key drop
cr s" ge'"        type ge' key drop
cr s" ge-"        type ge- key drop
cr s" ge="        type ge= key drop
cr s" gei["       type gei[ key drop
cr s" gen-"       type gen- key drop
cr s" gen="       type gen= key drop
cr s" geng-"      type geng- key drop
cr s" geng["      type geng[ key drop
cr s" geng]"      type geng] key drop
cr s" gen["       type gen[ key drop
cr s" gen]"       type gen] key drop
cr s" ge["        type ge[ key drop
cr s" ge]"        type ge] key drop
cr s" gou-"       type gou- key drop
cr s" gou["       type gou[ key drop
cr s" gou]"       type gou] key drop
cr s" gu'"        type gu' key drop
cr s" gu-"        type gu- key drop
cr s" gu="        type gu= key drop
cr s" gua-"       type gua- key drop
cr s" guai-"      type guai- key drop
cr s" guai["      type guai[ key drop
cr s" guai]"      type guai] key drop
cr s" guan-"      type guan- key drop
cr s" guang-"     type guang- key drop
cr s" guang["     type guang[ key drop
cr s" guang]"     type guang] key drop
cr s" guan["      type guan[ key drop
cr s" guan]"      type guan] key drop
cr s" gua["       type gua[ key drop
cr s" gua]"       type gua] key drop
cr s" guei'"      type guei' key drop
cr s" guei-"      type guei- key drop
cr s" guei["      type guei[ key drop
cr s" guei]"      type guei] key drop
cr s" guen["      type guen[ key drop
cr s" guen]"      type guen] key drop
cr s" gung-"      type gung- key drop
cr s" gung["      type gung[ key drop
cr s" gung]"      type gung] key drop
cr s" guo'"       type guo' key drop
cr s" guo-"       type guo- key drop
cr s" guo="       type guo= key drop
cr s" guo["       type guo[ key drop
cr s" guo]"       type guo] key drop
cr s" gu["        type gu[ key drop
cr s" gu]"        type gu] key drop
cr s" ha'"        type ha' key drop
cr s" ha-"        type ha- key drop
cr s" ha="        type ha= key drop
cr s" hai'"       type hai' key drop
cr s" hai-"       type hai- key drop
cr s" hai="       type hai= key drop
cr s" hai["       type hai[ key drop
cr s" hai]"       type hai] key drop
cr s" han-"       type han- key drop
cr s" han="       type han= key drop
cr s" hang-"      type hang- key drop
cr s" hang="      type hang= key drop
cr s" hang]"      type hang] key drop
cr s" han["       type han[ key drop
cr s" han]"       type han] key drop
cr s" hau-"       type hau- key drop
cr s" hau="       type hau= key drop
cr s" hau["       type hau[ key drop
cr s" hau]"       type hau] key drop
cr s" ha["        type ha[ key drop
cr s" ha]"        type ha] key drop
cr s" he'"        type he' key drop
cr s" he-"        type he- key drop
cr s" he="        type he= key drop
cr s" hei-"       type hei- key drop
cr s" hen="       type hen= key drop
cr s" heng'"      type heng' key drop
cr s" heng-"      type heng- key drop
cr s" heng="      type heng= key drop
cr s" heng]"      type heng] key drop
cr s" hen["       type hen[ key drop
cr s" hen]"       type hen] key drop
cr s" he]"        type he] key drop
cr s" hou'"       type hou' key drop
cr s" hou-"       type hou- key drop
cr s" hou="       type hou= key drop
cr s" hou["       type hou[ key drop
cr s" hou]"       type hou] key drop
cr s" hu'"        type hu' key drop
cr s" hu-"        type hu- key drop
cr s" hu="        type hu= key drop
cr s" hua'"       type hua' key drop
cr s" hua-"       type hua- key drop
cr s" hua="       type hua= key drop
cr s" huai="      type huai= key drop
cr s" huai]"      type huai] key drop
cr s" huan-"      type huan- key drop
cr s" huan="      type huan= key drop
cr s" huang'"     type huang' key drop
cr s" huang-"     type huang- key drop
cr s" huang="     type huang= key drop
cr s" huang["     type huang[ key drop
cr s" huang]"     type huang] key drop
cr s" huan["      type huan[ key drop
cr s" huan]"      type huan] key drop
cr s" hua["       type hua[ key drop
cr s" hua]"       type hua] key drop
cr s" huei'"      type huei' key drop
cr s" huei-"      type huei- key drop
cr s" huei="      type huei= key drop
cr s" huei["      type huei[ key drop
cr s" huei]"      type huei] key drop
cr s" huen-"      type huen- key drop
cr s" huen="      type huen= key drop
cr s" huen]"      type huen] key drop
cr s" hung-"      type hung- key drop
cr s" hung="      type hung= key drop
cr s" hung["      type hung[ key drop
cr s" hung]"      type hung] key drop
cr s" huo'"       type huo' key drop
cr s" huo-"       type huo- key drop
cr s" huo="       type huo= key drop
cr s" huo["       type huo[ key drop
cr s" huo]"       type huo] key drop
cr s" hu["        type hu[ key drop
cr s" hu]"        type hu] key drop
cr s" i'"         type i' key drop
cr s" i-"         type i- key drop
cr s" i="         type i= key drop
cr s" ia'"        type ia' key drop
cr s" ia-"        type ia- key drop
cr s" ia="        type ia= key drop
cr s" ian="       type ian= key drop
cr s" iang-"      type iang- key drop
cr s" iang="      type iang= key drop
cr s" iang["      type iang[ key drop
cr s" iang]"      type iang] key drop
cr s" ian["       type ian[ key drop
cr s" ian]"       type ian] key drop
cr s" iau-"       type iau- key drop
cr s" iau="       type iau= key drop
cr s" iau["       type iau[ key drop
cr s" iau]"       type iau] key drop
cr s" ia["        type ia[ key drop
cr s" ia]"        type ia] key drop
cr s" ie'"        type ie' key drop
cr s" ie-"        type ie- key drop
cr s" ie="        type ie= key drop
cr s" ie["        type ie[ key drop
cr s" ie]"        type ie] key drop
cr s" in-"        type in- key drop
cr s" in="        type in= key drop
cr s" ing'"       type ing' key drop
cr s" ing-"       type ing- key drop
cr s" ing="       type ing= key drop
cr s" ing["       type ing[ key drop
cr s" ing]"       type ing] key drop
cr s" in["        type in[ key drop
cr s" in]"        type in] key drop
cr s" io'"        type io' key drop
cr s" io-"        type io- key drop
cr s" iou-"       type iou- key drop
cr s" iou="       type iou= key drop
cr s" iou["       type iou[ key drop
cr s" iou]"       type iou] key drop
cr s" i["         type i[ key drop
cr s" i]"         type i] key drop
cr s" ja-"        type ja- key drop
cr s" ja="        type ja= key drop
cr s" jai-"       type jai- key drop
cr s" jai="       type jai= key drop
cr s" jai["       type jai[ key drop
cr s" jai]"       type jai] key drop
cr s" jan-"       type jan- key drop
cr s" jang-"      type jang- key drop
cr s" jang["      type jang[ key drop
cr s" jang]"      type jang] key drop
cr s" jan["       type jan[ key drop
cr s" jan]"       type jan] key drop
cr s" jau-"       type jau- key drop
cr s" jau="       type jau= key drop
cr s" jau["       type jau[ key drop
cr s" jau]"       type jau] key drop
cr s" ja["        type ja[ key drop
cr s" ja]"        type ja] key drop
cr s" je'"        type je' key drop
cr s" je-"        type je- key drop
cr s" je="        type je= key drop
cr s" jei]"       type jei] key drop
cr s" jen-"       type jen- key drop
cr s" jeng'"      type jeng' key drop
cr s" jeng-"      type jeng- key drop
cr s" jeng["      type jeng[ key drop
cr s" jeng]"      type jeng] key drop
cr s" jen["       type jen[ key drop
cr s" jen]"       type jen] key drop
cr s" je["        type je[ key drop
cr s" je]"        type je] key drop
cr s" ji'"        type ji' key drop
cr s" ji-"        type ji- key drop
cr s" ji="        type ji= key drop
cr s" jia'"       type jia' key drop
cr s" jia-"       type jia- key drop
cr s" jia="       type jia= key drop
cr s" jian'"      type jian' key drop
cr s" jian-"      type jian- key drop
cr s" jiang-"     type jiang- key drop
cr s" jiang["     type jiang[ key drop
cr s" jiang]"     type jiang] key drop
cr s" jian["      type jian[ key drop
cr s" jian]"      type jian] key drop
cr s" jiau-"      type jiau- key drop
cr s" jiau="      type jiau= key drop
cr s" jiau["      type jiau[ key drop
cr s" jiau]"      type jiau] key drop
cr s" jia["       type jia[ key drop
cr s" jia]"       type jia] key drop
cr s" jie'"       type jie' key drop
cr s" jie-"       type jie- key drop
cr s" jie="       type jie= key drop
cr s" jie["       type jie[ key drop
cr s" jie]"       type jie] key drop
cr s" jin-"       type jin- key drop
cr s" jing'"      type jing' key drop
cr s" jing-"      type jing- key drop
cr s" jing["      type jing[ key drop
cr s" jing]"      type jing] key drop
cr s" jin["       type jin[ key drop
cr s" jin]"       type jin] key drop
cr s" jiou'"      type jiou' key drop
cr s" jiou-"      type jiou- key drop
cr s" jiou["      type jiou[ key drop
cr s" jiou]"      type jiou] key drop
cr s" ji["        type ji[ key drop
cr s" ji]"        type ji] key drop
cr s" jou-"       type jou- key drop
cr s" jou="       type jou= key drop
cr s" jou["       type jou[ key drop
cr s" jou]"       type jou] key drop
cr s" ju-"        type ju- key drop
cr s" ju="        type ju= key drop
cr s" jua-"       type jua- key drop
cr s" juai-"      type juai- key drop
cr s" juai["      type juai[ key drop
cr s" juai]"      type juai] key drop
cr s" juan-"      type juan- key drop
cr s" juang-"     type juang- key drop
cr s" juang["     type juang[ key drop
cr s" juang]"     type juang] key drop
cr s" juan["      type juan[ key drop
cr s" juan]"      type juan] key drop
cr s" jua["       type jua[ key drop
cr s" juei-"      type juei- key drop
cr s" juei]"      type juei] key drop
cr s" jun-"       type jun- key drop
cr s" jung-"      type jung- key drop
cr s" jung["      type jung[ key drop
cr s" jung]"      type jung] key drop
cr s" jun["       type jun[ key drop
cr s" juo-"       type juo- key drop
cr s" juo="       type juo= key drop
cr s" ju["        type ju[ key drop
cr s" ju]"        type ju] key drop
cr s" jy'"        type jy' key drop
cr s" jy-"        type jy- key drop
cr s" jy="        type jy= key drop
cr s" jyu-"       type jyu- key drop
cr s" jyu="       type jyu= key drop
cr s" jyuan-"     type jyuan- key drop
cr s" jyuan["     type jyuan[ key drop
cr s" jyuan]"     type jyuan] key drop
cr s" jyue-"      type jyue- key drop
cr s" jyue="      type jyue= key drop
cr s" jyue["      type jyue[ key drop
cr s" jyue]"      type jyue] key drop
cr s" jyun-"      type jyun- key drop
cr s" jyung-"     type jyung- key drop
cr s" jyung["     type jyung[ key drop
cr s" jyun]"      type jyun] key drop
cr s" jyu["       type jyu[ key drop
cr s" jyu]"       type jyu] key drop
cr s" jy["        type jy[ key drop
cr s" jy]"        type jy] key drop
cr s" ka-"        type ka- key drop
cr s" kai-"       type kai- key drop
cr s" kai["       type kai[ key drop
cr s" kai]"       type kai] key drop
cr s" kan-"       type kan- key drop
cr s" kang-"      type kang- key drop
cr s" kang="      type kang= key drop
cr s" kang]"      type kang] key drop
cr s" kan["       type kan[ key drop
cr s" kan]"       type kan] key drop
cr s" kau-"       type kau- key drop
cr s" kau["       type kau[ key drop
cr s" kau]"       type kau] key drop
cr s" ka["        type ka[ key drop
cr s" ke'"        type ke' key drop
cr s" ke-"        type ke- key drop
cr s" ke="        type ke= key drop
cr s" kei-"       type kei- key drop
cr s" keng-"      type keng- key drop
cr s" ken["       type ken[ key drop
cr s" ke["        type ke[ key drop
cr s" ke]"        type ke] key drop
cr s" kou-"       type kou- key drop
cr s" kou["       type kou[ key drop
cr s" kou]"       type kou] key drop
cr s" ku-"        type ku- key drop
cr s" kua-"       type kua- key drop
cr s" kuai'"      type kuai' key drop
cr s" kuai["      type kuai[ key drop
cr s" kuai]"      type kuai] key drop
cr s" kuan-"      type kuan- key drop
cr s" kuang-"     type kuang- key drop
cr s" kuang="     type kuang= key drop
cr s" kuang]"     type kuang] key drop
cr s" kuan["      type kuan[ key drop
cr s" kua["       type kua[ key drop
cr s" kua]"       type kua] key drop
cr s" kuei-"      type kuei- key drop
cr s" kuei="      type kuei= key drop
cr s" kuei["      type kuei[ key drop
cr s" kuei]"      type kuei] key drop
cr s" kuen-"      type kuen- key drop
cr s" kuen["      type kuen[ key drop
cr s" kuen]"      type kuen] key drop
cr s" kung-"      type kung- key drop
cr s" kung["      type kung[ key drop
cr s" kung]"      type kung] key drop
cr s" kuo]"       type kuo] key drop
cr s" ku["        type ku[ key drop
cr s" ku]"        type ku] key drop
cr s" la'"        type la' key drop
cr s" la-"        type la- key drop
cr s" la="        type la= key drop
cr s" lai'"       type lai' key drop
cr s" lai="       type lai= key drop
cr s" lai]"       type lai] key drop
cr s" lan="       type lan= key drop
cr s" lang-"      type lang- key drop
cr s" lang="      type lang= key drop
cr s" lang["      type lang[ key drop
cr s" lang]"      type lang] key drop
cr s" lan["       type lan[ key drop
cr s" lan]"       type lan] key drop
cr s" lau'"       type lau' key drop
cr s" lau-"       type lau- key drop
cr s" lau="       type lau= key drop
cr s" lau["       type lau[ key drop
cr s" lau]"       type lau] key drop
cr s" la["        type la[ key drop
cr s" la]"        type la] key drop
cr s" le'"        type le' key drop
cr s" lei-"       type lei- key drop
cr s" lei="       type lei= key drop
cr s" lei["       type lei[ key drop
cr s" lei]"       type lei] key drop
cr s" leng="      type leng= key drop
cr s" leng["      type leng[ key drop
cr s" leng]"      type leng] key drop
cr s" le]"        type le] key drop
cr s" li'"        type li' key drop
cr s" li-"        type li- key drop
cr s" li="        type li= key drop
cr s" lian="      type lian= key drop
cr s" liang'"     type liang' key drop
cr s" liang="     type liang= key drop
cr s" liang["     type liang[ key drop
cr s" liang]"     type liang] key drop
cr s" lian["      type lian[ key drop
cr s" lian]"      type lian] key drop
cr s" liau-"      type liau- key drop
cr s" liau="      type liau= key drop
cr s" liau["      type liau[ key drop
cr s" liau]"      type liau] key drop
cr s" lia["       type lia[ key drop
cr s" lie-"       type lie- key drop
cr s" lie["       type lie[ key drop
cr s" lie]"       type lie] key drop
cr s" lin="       type lin= key drop
cr s" ling-"      type ling- key drop
cr s" ling="      type ling= key drop
cr s" ling["      type ling[ key drop
cr s" ling]"      type ling] key drop
cr s" lin["       type lin[ key drop
cr s" lin]"       type lin] key drop
cr s" liou-"      type liou- key drop
cr s" liou="      type liou= key drop
cr s" liou["      type liou[ key drop
cr s" liou]"      type liou] key drop
cr s" li["        type li[ key drop
cr s" li]"        type li] key drop
cr s" lo'"        type lo' key drop
cr s" lou'"       type lou' key drop
cr s" lou-"       type lou- key drop
cr s" lou="       type lou= key drop
cr s" lou["       type lou[ key drop
cr s" lou]"       type lou] key drop
cr s" lu'"        type lu' key drop
cr s" lu-"        type lu- key drop
cr s" lu="        type lu= key drop
cr s" luan="      type luan= key drop
cr s" luan["      type luan[ key drop
cr s" luan]"      type luan] key drop
cr s" luen-"      type luen- key drop
cr s" luen="      type luen= key drop
cr s" luen]"      type luen] key drop
cr s" lung'"      type lung' key drop
cr s" lung-"      type lung- key drop
cr s" lung="      type lung= key drop
cr s" lung["      type lung[ key drop
cr s" lung]"      type lung] key drop
cr s" luo-"       type luo- key drop
cr s" luo="       type luo= key drop
cr s" luo["       type luo[ key drop
cr s" luo]"       type luo] key drop
cr s" lu["        type lu[ key drop
cr s" lu]"        type lu] key drop
cr s" lyu="       type lyu= key drop
cr s" lyue]"      type lyue] key drop
cr s" lyu["       type lyu[ key drop
cr s" lyu]"       type lyu] key drop
cr s" ma'"        type ma' key drop
cr s" ma-"        type ma- key drop
cr s" ma="        type ma= key drop
cr s" mai'"       type mai' key drop
cr s" mai="       type mai= key drop
cr s" mai["       type mai[ key drop
cr s" mai]"       type mai] key drop
cr s" man-"       type man- key drop
cr s" man="       type man= key drop
cr s" mang="      type mang= key drop
cr s" mang["      type mang[ key drop
cr s" man["       type man[ key drop
cr s" man]"       type man] key drop
cr s" mau'"       type mau' key drop
cr s" mau-"       type mau- key drop
cr s" mau="       type mau= key drop
cr s" mau["       type mau[ key drop
cr s" mau]"       type mau] key drop
cr s" ma["        type ma[ key drop
cr s" ma]"        type ma] key drop
cr s" me'"        type me' key drop
cr s" me="        type me= key drop
cr s" mei'"       type mei' key drop
cr s" mei="       type mei= key drop
cr s" mei["       type mei[ key drop
cr s" mei]"       type mei] key drop
cr s" men'"       type men' key drop
cr s" men-"       type men- key drop
cr s" men="       type men= key drop
cr s" meng-"      type meng- key drop
cr s" meng="      type meng= key drop
cr s" meng["      type meng[ key drop
cr s" meng]"      type meng] key drop
cr s" men]"       type men] key drop
cr s" me]"        type me] key drop
cr s" mi-"        type mi- key drop
cr s" mi="        type mi= key drop
cr s" mian'"      type mian' key drop
cr s" mian="      type mian= key drop
cr s" mian["      type mian[ key drop
cr s" mian]"      type mian] key drop
cr s" miau-"      type miau- key drop
cr s" miau="      type miau= key drop
cr s" miau["      type miau[ key drop
cr s" miau]"      type miau] key drop
cr s" mie-"       type mie- key drop
cr s" mie]"       type mie] key drop
cr s" min="       type min= key drop
cr s" ming'"      type ming' key drop
cr s" ming="      type ming= key drop
cr s" ming["      type ming[ key drop
cr s" ming]"      type ming] key drop
cr s" min["       type min[ key drop
cr s" miou]"      type miou] key drop
cr s" mi["        type mi[ key drop
cr s" mi]"        type mi] key drop
cr s" mo'"        type mo' key drop
cr s" mo-"        type mo- key drop
cr s" mo="        type mo= key drop
cr s" mou-"       type mou- key drop
cr s" mou="       type mou= key drop
cr s" mou["       type mou[ key drop
cr s" mo["        type mo[ key drop
cr s" mo]"        type mo] key drop
cr s" mu="        type mu= key drop
cr s" mu["        type mu[ key drop
cr s" mu]"        type mu] key drop
cr s" na'"        type na' key drop
cr s" na-"        type na- key drop
cr s" na="        type na= key drop
cr s" nai'"       type nai' key drop
cr s" nai["       type nai[ key drop
cr s" nai]"       type nai] key drop
cr s" nan'"       type nan' key drop
cr s" nan-"       type nan- key drop
cr s" nan="       type nan= key drop
cr s" nang-"      type nang- key drop
cr s" nang="      type nang= key drop
cr s" nang["      type nang[ key drop
cr s" nang]"      type nang] key drop
cr s" nan["       type nan[ key drop
cr s" nan]"       type nan] key drop
cr s" nau'"       type nau' key drop
cr s" nau-"       type nau- key drop
cr s" nau="       type nau= key drop
cr s" nau["       type nau[ key drop
cr s" nau]"       type nau] key drop
cr s" na["        type na[ key drop
cr s" na]"        type na] key drop
cr s" ne'"        type ne' key drop
cr s" nei["       type nei[ key drop
cr s" nei]"       type nei] key drop
cr s" neng="      type neng= key drop
cr s" nen]"       type nen] key drop
cr s" ne]"        type ne] key drop
cr s" ni-"        type ni- key drop
cr s" ni="        type ni= key drop
cr s" nian-"      type nian- key drop
cr s" nian="      type nian= key drop
cr s" niang'"     type niang' key drop
cr s" niang="     type niang= key drop
cr s" niang]"     type niang] key drop
cr s" nian["      type nian[ key drop
cr s" nian]"      type nian] key drop
cr s" niau["      type niau[ key drop
cr s" niau]"      type niau] key drop
cr s" nie-"       type nie- key drop
cr s" nie="       type nie= key drop
cr s" nie]"       type nie] key drop
cr s" nin="       type nin= key drop
cr s" ning="      type ning= key drop
cr s" ning["      type ning[ key drop
cr s" ning]"      type ning] key drop
cr s" niou-"      type niou- key drop
cr s" niou="      type niou= key drop
cr s" niou["      type niou[ key drop
cr s" niou]"      type niou] key drop
cr s" ni["        type ni[ key drop
cr s" ni]"        type ni] key drop
cr s" nou]"       type nou] key drop
cr s" nu="        type nu= key drop
cr s" nuan["      type nuan[ key drop
cr s" nung="      type nung= key drop
cr s" nung]"      type nung] key drop
cr s" nuo="       type nuo= key drop
cr s" nuo]"       type nuo] key drop
cr s" nu["        type nu[ key drop
cr s" nu]"        type nu] key drop
cr s" nyue]"      type nyue] key drop
cr s" nyu["       type nyu[ key drop
cr s" nyu]"       type nyu] key drop
cr s" o-"         type o- key drop
cr s" cr s"       type o= key drop
cr s" ou-"        type ou- key drop
cr s" ou["        type ou[ key drop
cr s" ou]"        type ou] key drop
cr s" o["         type o[ key drop
cr s" o]"         type o] key drop
cr s" pa-"        type pa- key drop
cr s" pa="        type pa= key drop
cr s" pai-"       type pai- key drop
cr s" pai="       type pai= key drop
cr s" pai["       type pai[ key drop
cr s" pai]"       type pai] key drop
cr s" pan-"       type pan- key drop
cr s" pan="       type pan= key drop
cr s" pang-"      type pang- key drop
cr s" pang="      type pang= key drop
cr s" pang["      type pang[ key drop
cr s" pang]"      type pang] key drop
cr s" pan]"       type pan] key drop
cr s" pau-"       type pau- key drop
cr s" pau="       type pau= key drop
cr s" pau["       type pau[ key drop
cr s" pau]"       type pau] key drop
cr s" pa]"        type pa] key drop
cr s" pei-"       type pei- key drop
cr s" pei="       type pei= key drop
cr s" pei]"       type pei] key drop
cr s" pen-"       type pen- key drop
cr s" pen="       type pen= key drop
cr s" peng-"      type peng- key drop
cr s" peng="      type peng= key drop
cr s" peng["      type peng[ key drop
cr s" peng]"      type peng] key drop
cr s" pen]"       type pen] key drop
cr s" pi-"        type pi- key drop
cr s" pi="        type pi= key drop
cr s" pian-"      type pian- key drop
cr s" pian="      type pian= key drop
cr s" pian["      type pian[ key drop
cr s" pian]"      type pian] key drop
cr s" piau-"      type piau- key drop
cr s" piau="      type piau= key drop
cr s" piau["      type piau[ key drop
cr s" piau]"      type piau] key drop
cr s" pie-"       type pie- key drop
cr s" pie["       type pie[ key drop
cr s" pin-"       type pin- key drop
cr s" pin="       type pin= key drop
cr s" ping-"      type ping- key drop
cr s" ping="      type ping= key drop
cr s" pin["       type pin[ key drop
cr s" pin]"       type pin] key drop
cr s" pi["        type pi[ key drop
cr s" pi]"        type pi] key drop
cr s" po'"        type po' key drop
cr s" po-"        type po- key drop
cr s" po="        type po= key drop
cr s" pou-"       type pou- key drop
cr s" pou="       type pou= key drop
cr s" pou["       type pou[ key drop
cr s" po["        type po[ key drop
cr s" po]"        type po] key drop
cr s" pu-"        type pu- key drop
cr s" pu="        type pu= key drop
cr s" pu["        type pu[ key drop
cr s" pu]"        type pu] key drop
cr s" ran="       type ran= key drop
cr s" rang-"      type rang- key drop
cr s" rang="      type rang= key drop
cr s" rang["      type rang[ key drop
cr s" rang]"      type rang] key drop
cr s" ran["       type ran[ key drop
cr s" rau="       type rau= key drop
cr s" rau["       type rau[ key drop
cr s" rau]"       type rau] key drop
cr s" ren'"       type ren' key drop
cr s" ren="       type ren= key drop
cr s" reng-"      type reng- key drop
cr s" reng="      type reng= key drop
cr s" ren["       type ren[ key drop
cr s" ren]"       type ren] key drop
cr s" re["        type re[ key drop
cr s" re]"        type re] key drop
cr s" rou="       type rou= key drop
cr s" rou]"       type rou] key drop
cr s" ru="        type ru= key drop
cr s" ruan["      type ruan[ key drop
cr s" ruei["      type ruei[ key drop
cr s" ruei]"      type ruei] key drop
cr s" rung="      type rung= key drop
cr s" rung["      type rung[ key drop
cr s" run]"       type run] key drop
cr s" ruo]"       type ruo] key drop
cr s" ru["        type ru[ key drop
cr s" ru]"        type ru] key drop
cr s" ry]"        type ry] key drop
cr s" sha-"       type sha- key drop
cr s" shai-"      type shai- key drop
cr s" shai["      type shai[ key drop
cr s" shai]"      type shai] key drop
cr s" shan-"      type shan- key drop
cr s" shang'"     type shang' key drop
cr s" shang-"     type shang- key drop
cr s" shang["     type shang[ key drop
cr s" shang]"     type shang] key drop
cr s" shan["      type shan[ key drop
cr s" shan]"      type shan] key drop
cr s" shau'"      type shau' key drop
cr s" shau-"      type shau- key drop
cr s" shau="      type shau= key drop
cr s" shau["      type shau[ key drop
cr s" shau]"      type shau] key drop
cr s" sha["       type sha[ key drop
cr s" sha]"       type sha] key drop
cr s" she-"       type she- key drop
cr s" she="       type she= key drop
cr s" shei="      type shei= key drop
cr s" shen'"      type shen' key drop
cr s" shen-"      type shen- key drop
cr s" shen="      type shen= key drop
cr s" sheng'"     type sheng' key drop
cr s" sheng-"     type sheng- key drop
cr s" sheng="     type sheng= key drop
cr s" sheng["     type sheng[ key drop
cr s" sheng]"     type sheng] key drop
cr s" shen["      type shen[ key drop
cr s" shen]"      type shen] key drop
cr s" she["       type she[ key drop
cr s" she]"       type she] key drop
cr s" shi'"       type shi' key drop
cr s" shi-"       type shi- key drop
cr s" shi="       type shi= key drop
cr s" shia'"      type shia' key drop
cr s" shia-"      type shia- key drop
cr s" shia="      type shia= key drop
cr s" shian-"     type shian- key drop
cr s" shian="     type shian= key drop
cr s" shiang-"    type shiang- key drop
cr s" shiang="    type shiang= key drop
cr s" shiang["    type shiang[ key drop
cr s" shiang]"    type shiang] key drop
cr s" shian["     type shian[ key drop
cr s" shian]"     type shian] key drop
cr s" shiau-"     type shiau- key drop
cr s" shiau="     type shiau= key drop
cr s" shiau["     type shiau[ key drop
cr s" shiau]"     type shiau] key drop
cr s" shia]"      type shia] key drop
cr s" shie'"      type shie' key drop
cr s" shie-"      type shie- key drop
cr s" shie="      type shie= key drop
cr s" shie["      type shie[ key drop
cr s" shie]"      type shie] key drop
cr s" shin-"      type shin- key drop
cr s" shin="      type shin= key drop
cr s" shing'"     type shing' key drop
cr s" shing-"     type shing- key drop
cr s" shing="     type shing= key drop
cr s" shing["     type shing[ key drop
cr s" shing]"     type shing] key drop
cr s" shin]"      type shin] key drop
cr s" shiou-"     type shiou- key drop
cr s" shiou["     type shiou[ key drop
cr s" shiou]"     type shiou] key drop
cr s" shi["       type shi[ key drop
cr s" shi]"       type shi] key drop
cr s" shou-"      type shou- key drop
cr s" shou["      type shou[ key drop
cr s" shou]"      type shou] key drop
cr s" shu'"       type shu' key drop
cr s" shu-"       type shu- key drop
cr s" shu="       type shu= key drop
cr s" shua-"      type shua- key drop
cr s" shuai-"     type shuai- key drop
cr s" shuai["     type shuai[ key drop
cr s" shuai]"     type shuai] key drop
cr s" shuan-"     type shuan- key drop
cr s" shuang-"    type shuang- key drop
cr s" shuang["    type shuang[ key drop
cr s" shuan]"     type shuan] key drop
cr s" shua["      type shua[ key drop
cr s" shua]"      type shua] key drop
cr s" shuei="     type shuei= key drop
cr s" shuei["     type shuei[ key drop
cr s" shuei]"     type shuei] key drop
cr s" shun["      type shun[ key drop
cr s" shun]"      type shun] key drop
cr s" shuo-"      type shuo- key drop
cr s" shuo]"      type shuo] key drop
cr s" shu["       type shu[ key drop
cr s" shu]"       type shu] key drop
cr s" shy'"       type shy' key drop
cr s" shy-"       type shy- key drop
cr s" shy="       type shy= key drop
cr s" shyu'"      type shyu' key drop
cr s" shyu-"      type shyu- key drop
cr s" shyu="      type shyu= key drop
cr s" shyuan-"    type shyuan- key drop
cr s" shyuan="    type shyuan= key drop
cr s" shyuan["    type shyuan[ key drop
cr s" shyuan]"    type shyuan] key drop
cr s" shyue-"     type shyue- key drop
cr s" shyue="     type shyue= key drop
cr s" shyue["     type shyue[ key drop
cr s" shyue]"     type shyue] key drop
cr s" shyun-"     type shyun- key drop
cr s" shyun="     type shyun= key drop
cr s" shyung'"    type shyung' key drop
cr s" shyung-"    type shyung- key drop
cr s" shyung="    type shyung= key drop
cr s" shyun]"     type shyun] key drop
cr s" shyu["      type shyu[ key drop
cr s" shyu]"      type shyu] key drop
cr s" shy["       type shy[ key drop
cr s" shy]"       type shy] key drop
cr s" ta-"        type ta- key drop
cr s" tai'"       type tai' key drop
cr s" tai-"       type tai- key drop
cr s" tai="       type tai= key drop
cr s" tai]"       type tai] key drop
cr s" tan-"       type tan- key drop
cr s" tan="       type tan= key drop
cr s" tang-"      type tang- key drop
cr s" tang="      type tang= key drop
cr s" tang["      type tang[ key drop
cr s" tang]"      type tang] key drop
cr s" tan["       type tan[ key drop
cr s" tan]"       type tan] key drop
cr s" tau'"       type tau' key drop
cr s" tau-"       type tau- key drop
cr s" tau="       type tau= key drop
cr s" tau["       type tau[ key drop
cr s" tau]"       type tau] key drop
cr s" ta["        type ta[ key drop
cr s" ta]"        type ta] key drop
cr s" tei-"       type tei- key drop
cr s" teng-"      type teng- key drop
cr s" teng="      type teng= key drop
cr s" te]"        type te] key drop
cr s" ti-"        type ti- key drop
cr s" ti="        type ti= key drop
cr s" tian'"      type tian' key drop
cr s" tian-"      type tian- key drop
cr s" tian="      type tian= key drop
cr s" tian["      type tian[ key drop
cr s" tiau-"      type tiau- key drop
cr s" tiau="      type tiau= key drop
cr s" tiau["      type tiau[ key drop
cr s" tiau]"      type tiau] key drop
cr s" tie-"       type tie- key drop
cr s" tie["       type tie[ key drop
cr s" tie]"       type tie] key drop
cr s" ting-"      type ting- key drop
cr s" ting="      type ting= key drop
cr s" ting["      type ting[ key drop
cr s" ti["        type ti[ key drop
cr s" ti]"        type ti] key drop
cr s" tou'"       type tou' key drop
cr s" tou-"       type tou- key drop
cr s" tou="       type tou= key drop
cr s" tou]"       type tou] key drop
cr s" tsa-"       type tsa- key drop
cr s" tsai-"      type tsai- key drop
cr s" tsai="      type tsai= key drop
cr s" tsai["      type tsai[ key drop
cr s" tsai]"      type tsai] key drop
cr s" tsan-"      type tsan- key drop
cr s" tsan="      type tsan= key drop
cr s" tsang-"     type tsang- key drop
cr s" tsang="     type tsang= key drop
cr s" tsan["      type tsan[ key drop
cr s" tsan]"      type tsan] key drop
cr s" tsau-"      type tsau- key drop
cr s" tsau="      type tsau= key drop
cr s" tsau["      type tsau[ key drop
cr s" tsa["       type tsa[ key drop
cr s" tsen-"      type tsen- key drop
cr s" tsen="      type tsen= key drop
cr s" tseng-"     type tseng- key drop
cr s" tseng="     type tseng= key drop
cr s" tse]"       type tse] key drop
cr s" tsu-"       type tsu- key drop
cr s" tsuan-"     type tsuan- key drop
cr s" tsuan="     type tsuan= key drop
cr s" tsuan]"     type tsuan] key drop
cr s" tsuei-"     type tsuei- key drop
cr s" tsuei["     type tsuei[ key drop
cr s" tsuei]"     type tsuei] key drop
cr s" tsuen-"     type tsuen- key drop
cr s" tsuen="     type tsuen= key drop
cr s" tsuen["     type tsuen[ key drop
cr s" tsuen]"     type tsuen] key drop
cr s" tsung-"     type tsung- key drop
cr s" tsung="     type tsung= key drop
cr s" tsung]"     type tsung] key drop
cr s" tsuo-"      type tsuo- key drop
cr s" tsuo="      type tsuo= key drop
cr s" tsuo]"      type tsuo] key drop
cr s" tsu]"       type tsu] key drop
cr s" tsy'"       type tsy' key drop
cr s" tsy-"       type tsy- key drop
cr s" tsy="       type tsy= key drop
cr s" tsy["       type tsy[ key drop
cr s" tsy]"       type tsy] key drop
cr s" tu'"        type tu' key drop
cr s" tu-"        type tu- key drop
cr s" tu="        type tu= key drop
cr s" tuan-"      type tuan- key drop
cr s" tuan="      type tuan= key drop
cr s" tuei-"      type tuei- key drop
cr s" tuei="      type tuei= key drop
cr s" tuei["      type tuei[ key drop
cr s" tuei]"      type tuei] key drop
cr s" tun-"       type tun- key drop
cr s" tun="       type tun= key drop
cr s" tung'"      type tung' key drop
cr s" tung-"      type tung- key drop
cr s" tung="      type tung= key drop
cr s" tung["      type tung[ key drop
cr s" tung]"      type tung] key drop
cr s" tun["       type tun[ key drop
cr s" tun]"       type tun] key drop
cr s" tuo'"       type tuo' key drop
cr s" tuo-"       type tuo- key drop
cr s" tuo="       type tuo= key drop
cr s" tuo["       type tuo[ key drop
cr s" tuo]"       type tuo] key drop
cr s" tu["        type tu[ key drop
cr s" tu]"        type tu] key drop
cr s" u'"         type u' key drop
cr s" u-"         type u- key drop
cr s" u="         type u= key drop
cr s" ua'"        type ua' key drop
cr s" ua-"        type ua- key drop
cr s" ua="        type ua= key drop
cr s" uai'"       type uai' key drop
cr s" uai-"       type uai- key drop
cr s" uai["       type uai[ key drop
cr s" uai]"       type uai] key drop
cr s" uan-"       type uan- key drop
cr s" uan="       type uan= key drop
cr s" uang'"      type uang' key drop
cr s" uang-"      type uang- key drop
cr s" uang="      type uang= key drop
cr s" uang["      type uang[ key drop
cr s" uang]"      type uang] key drop
cr s" uan["       type uan[ key drop
cr s" uan]"       type uan] key drop
cr s" ua["        type ua[ key drop
cr s" ua]"        type ua] key drop
cr s" uei'"       type uei' key drop
cr s" uei-"       type uei- key drop
cr s" uei="       type uei= key drop
cr s" uei["       type uei[ key drop
cr s" uei]"       type uei] key drop
cr s" uen'"       type uen' key drop
cr s" uen-"       type uen- key drop
cr s" uen="       type uen= key drop
cr s" uen["       type uen[ key drop
cr s" uen]"       type uen] key drop
cr s" ung-"       type ung- key drop
cr s" ung["       type ung[ key drop
cr s" ung]"       type ung] key drop
cr s" uo-"        type uo- key drop
cr s" uo["        type uo[ key drop
cr s" uo]"        type uo] key drop
cr s" u["         type u[ key drop
cr s" u]"         type u] key drop
cr s" xa-"        type xa- key drop
cr s" xai-"       type xai- key drop
cr s" xai]"       type xai] key drop
cr s" xan-"       type xan- key drop
cr s" xang-"      type xang- key drop
cr s" xang["      type xang[ key drop
cr s" xang]"      type xang] key drop
cr s" xan["       type xan[ key drop
cr s" xan]"       type xan] key drop
cr s" xau-"       type xau- key drop
cr s" xau["       type xau[ key drop
cr s" xau]"       type xau] key drop
cr s" xa["        type xa[ key drop
cr s" xa]"        type xa] key drop
cr s" xen-"       type xen- key drop
cr s" xeng-"      type xeng- key drop
cr s" xe]"        type xe] key drop
cr s" xou'"       type xou' key drop
cr s" xou-"       type xou- key drop
cr s" xou["       type xou[ key drop
cr s" xou]"       type xou] key drop
cr s" xu'"        type xu' key drop
cr s" xu-"        type xu- key drop
cr s" xu="        type xu= key drop
cr s" xuan-"      type xuan- key drop
cr s" xuan]"      type xuan] key drop
cr s" xuei-"      type xuei- key drop
cr s" xuei="      type xuei= key drop
cr s" xuei["      type xuei[ key drop
cr s" xuei]"      type xuei] key drop
cr s" xun-"       type xun- key drop
cr s" xung-"      type xung- key drop
cr s" xung["      type xung[ key drop
cr s" xung]"      type xung] key drop
cr s" xun["       type xun[ key drop
cr s" xuo'"       type xuo' key drop
cr s" xuo-"       type xuo- key drop
cr s" xuo["       type xuo[ key drop
cr s" xu]"        type xu] key drop
cr s" xy'"        type xy' key drop
cr s" xy-"        type xy- key drop
cr s" xy["        type xy[ key drop
cr s" xy]"        type xy] key drop
cr s" you0"       type you0 key drop
cr s" yu'"        type yu' key drop
cr s" yu-"        type yu- key drop
cr s" yu="        type yu= key drop
cr s" yuan-"      type yuan- key drop
cr s" yuan="      type yuan= key drop
cr s" yuan["      type yuan[ key drop
cr s" yuan]"      type yuan] key drop
cr s" yue-"       type yue- key drop
cr s" yue]"       type yue] key drop
cr s" yun-"       type yun- key drop
cr s" yun="       type yun= key drop
cr s" yung-"      type yung- key drop
cr s" yung="      type yung= key drop
cr s" yung["      type yung[ key drop
cr s" yung]"      type yung] key drop
cr s" yun["       type yun[ key drop
cr s" yun]"       type yun] key drop
cr s" yu["        type yu[ key drop
cr s" yu]"        type yu] key drop
cr s" za-"        type za- key drop
cr s" za="        type za= key drop
cr s" zai'"       type zai' key drop
cr s" zai-"       type zai- key drop
cr s" zai["       type zai[ key drop
cr s" zai]"       type zai] key drop
cr s" zan'"       type zan' key drop
cr s" zan-"       type zan- key drop
cr s" zan="       type zan= key drop
cr s" zang-"      type zang- key drop
cr s" zang["      type zang[ key drop
cr s" zang]"      type zang] key drop
cr s" zan["       type zan[ key drop
cr s" zan]"       type zan] key drop
cr s" zau-"       type zau- key drop
cr s" zau="       type zau= key drop
cr s" zau["       type zau[ key drop
cr s" zau]"       type zau] key drop
cr s" za["        type za[ key drop
cr s" ze="        type ze= key drop
cr s" zei="       type zei= key drop
cr s" zeng-"      type zeng- key drop
cr s" zeng]"      type zeng] key drop
cr s" zen["       type zen[ key drop
cr s" zen]"       type zen] key drop
cr s" ze]"        type ze] key drop
cr s" zou-"       type zou- key drop
cr s" zou["       type zou[ key drop
cr s" zou]"       type zou] key drop
cr s" zu-"        type zu- key drop
cr s" zu="        type zu= key drop
cr s" zuan-"      type zuan- key drop
cr s" zuan["      type zuan[ key drop
cr s" zuan]"      type zuan] key drop
cr s" zui["       type zui[ key drop
cr s" zui]"       type zui] key drop
cr s" zun-"       type zun- key drop
cr s" zung-"      type zung- key drop
cr s" zung["      type zung[ key drop
cr s" zung]"      type zung] key drop
cr s" zun["       type zun[ key drop
cr s" zuo-"       type zuo- key drop
cr s" zuo="       type zuo= key drop
cr s" zuo["       type zuo[ key drop
cr s" zuo]"       type zuo] key drop
cr s" zu["        type zu[ key drop
cr s" zy'"        type zy' key drop
cr s" zy-"        type zy- key drop
cr s" zy["        type zy[ key drop
cr s" zy]"        type zy] key drop

