of ha' endof
of ha- endof
of ha= endof
of hai' endof
of hai- endof
of hai= endof
of hai[ endof
of hai] endof
of han- endof
of han= endof
of hang- endof
of hang= endof
of hang] endof
of han[ endof
of han] endof
of hau- endof
of hau= endof
of hau[ endof
of hau] endof
of ha[ endof
of ha] endof
of he' endof
of he- endof
of he= endof
of hei- endof
of hen= endof
of heng' endof
of heng- endof
of heng= endof
of heng] endof
of hen[ endof
of hen] endof
of he] endof
of hou' endof
of hou- endof
of hou= endof
of hou[ endof
of hou] endof
of hu' endof
of hu- endof
of hu= endof
of hua' endof
of hua- endof
of hua= endof
of huai= endof
of huai] endof
of huan- endof
of huan= endof
of huang' endof
of huang- endof
of huang= endof
of huang[ endof
of huang] endof
of huan[ endof
of huan] endof
of hua[ endof
of hua] endof
of huei' endof
of huei- endof
of huei= endof
of huei[ endof
of huei] endof
of huen- endof
of huen= endof
of huen] endof
of hung- endof
of hung= endof
of hung[ endof
of hung] endof
of huo' endof
of huo- endof
of huo= endof
of huo[ endof
of huo] endof
of hu[ endof
of hu] endof
