of ta- endof
of tai' endof
of tai- endof
of tai= endof
of tai] endof
of tan- endof
of tan= endof
of tang- endof
of tang= endof
of tang[ endof
of tang] endof
of tan[ endof
of tan] endof
of tau' endof
of tau- endof
of tau= endof
of tau[ endof
of tau] endof
of ta[ endof
of ta] endof
of tei- endof
of teng- endof
of teng= endof
of te] endof
of ti- endof
of ti= endof
of tian' endof
of tian- endof
of tian= endof
of tian[ endof
of tiau- endof
of tiau= endof
of tiau[ endof
of tiau] endof
of tie- endof
of tie[ endof
of tie] endof
of ting- endof
of ting= endof
of ting[ endof
of ti[ endof
of ti] endof
of tou' endof
of tou- endof
of tou= endof
of tou] endof
of tsa- endof
of tsai- endof
of tsai= endof
of tsai[ endof
of tsai] endof
of tsan- endof
of tsan= endof
of tsang- endof
of tsang= endof
of tsan[ endof
of tsan] endof
of tsau- endof
of tsau= endof
of tsau[ endof
of tsa[ endof
of tsen- endof
of tsen= endof
of tseng- endof
of tseng= endof
of tse] endof
of tsu- endof
of tsuan- endof
of tsuan= endof
of tsuan] endof
of tsuei- endof
of tsuei[ endof
of tsuei] endof
of tsuen- endof
of tsuen= endof
of tsuen[ endof
of tsuen] endof
of tsung- endof
of tsung= endof
of tsung] endof
of tsuo- endof
of tsuo= endof
of tsuo] endof
of tsu] endof
of tsy' endof
of tsy- endof
of tsy= endof
of tsy[ endof
of tsy] endof
of tu' endof
of tu- endof
of tu= endof
of tuan- endof
of tuan= endof
of tuei- endof
of tuei= endof
of tuei[ endof
of tuei] endof
of tun- endof
of tun= endof
of tung' endof
of tung- endof
of tung= endof
of tung[ endof
of tung] endof
of tun[ endof
of tun] endof
of tuo' endof
of tuo- endof
of tuo= endof
of tuo[ endof
of tuo] endof
of tu[ endof
of tu] endof
