of ja- endof
of ja= endof
of jai- endof
of jai= endof
of jai[ endof
of jai] endof
of jan- endof
of jang- endof
of jang[ endof
of jang] endof
of jan[ endof
of jan] endof
of jau- endof
of jau= endof
of jau[ endof
of jau] endof
of ja[ endof
of ja] endof
of je' endof
of je- endof
of je= endof
of jei] endof
of jen- endof
of jeng' endof
of jeng- endof
of jeng[ endof
of jeng] endof
of jen[ endof
of jen] endof
of je[ endof
of je] endof
of ji' endof
of ji- endof
of ji= endof
of jia' endof
of jia- endof
of jia= endof
of jian' endof
of jian- endof
of jiang- endof
of jiang[ endof
of jiang] endof
of jian[ endof
of jian] endof
of jiau- endof
of jiau= endof
of jiau[ endof
of jiau] endof
of jia[ endof
of jia] endof
of jie' endof
of jie- endof
of jie= endof
of jie[ endof
of jie] endof
of jin- endof
of jing' endof
of jing- endof
of jing[ endof
of jing] endof
of jin[ endof
of jin] endof
of jiou' endof
of jiou- endof
of jiou[ endof
of jiou] endof
of ji[ endof
of ji] endof
of jou- endof
of jou= endof
of jou[ endof
of jou] endof
of ju- endof
of ju= endof
of jua- endof
of juai- endof
of juai[ endof
of juai] endof
of juan- endof
of juang- endof
of juang[ endof
of juang] endof
of juan[ endof
of juan] endof
of jua[ endof
of juei- endof
of juei] endof
of jun- endof
of jung- endof
of jung[ endof
of jung] endof
of jun[ endof
of juo- endof
of juo= endof
of ju[ endof
of ju] endof
of jy' endof
of jy- endof
of jy= endof
of jyu- endof
of jyu= endof
of jyuan- endof
of jyuan[ endof
of jyuan] endof
of jyue- endof
of jyue= endof
of jyue[ endof
of jyue] endof
of jyun- endof
of jyung- endof
of jyung[ endof
of jyun] endof
of jyu[ endof
of jyu] endof
of jy[ endof
of jy] endof
