of ka- endof
of kai- endof
of kai[ endof
of kai] endof
of kan- endof
of kang- endof
of kang= endof
of kang] endof
of kan[ endof
of kan] endof
of kau- endof
of kau[ endof
of kau] endof
of ka[ endof
of ke' endof
of ke- endof
of ke= endof
of kei- endof
of keng- endof
of ken[ endof
of ke[ endof
of ke] endof
of kou- endof
of kou[ endof
of kou] endof
of ku- endof
of kua- endof
of kuai' endof
of kuai[ endof
of kuai] endof
of kuan- endof
of kuang- endof
of kuang= endof
of kuang] endof
of kuan[ endof
of kua[ endof
of kua] endof
of kuei- endof
of kuei= endof
of kuei[ endof
of kuei] endof
of kuen- endof
of kuen[ endof
of kuen] endof
of kung- endof
of kung[ endof
of kung] endof
of kuo] endof
of ku[ endof
of ku] endof