of na' endof
of na- endof
of na= endof
of nai' endof
of nai[ endof
of nai] endof
of nan' endof
of nan- endof
of nan= endof
of nang- endof
of nang= endof
of nang[ endof
of nang] endof
of nan[ endof
of nan] endof
of nau' endof
of nau- endof
of nau= endof
of nau[ endof
of nau] endof
of na[ endof
of na] endof
of ne' endof
of nei[ endof
of nei] endof
of neng= endof
of nen] endof
of ne] endof
of ni- endof
of ni= endof
of nian- endof
of nian= endof
of niang' endof
of niang= endof
of niang] endof
of nian[ endof
of nian] endof
of niau[ endof
of niau] endof
of nie- endof
of nie= endof
of nie] endof
of nin= endof
of ning= endof
of ning[ endof
of ning] endof
of niou- endof
of niou= endof
of niou[ endof
of niou] endof
of ni[ endof
of ni] endof
of nou] endof
of nu= endof
of nuan[ endof
of nung= endof
of nung] endof
of nuo= endof
of nuo] endof
of nu[ endof
of nu] endof
of nyue] endof
of nyu[ endof
of nyu] endof
