of e- endof
of e= endof
of ei= endof
of ei[ endof
of ei] endof
of en- endof
of eng' endof
of eng= endof
of eng[ endof
of eng] endof
of en] endof
of er= endof
of er[ endof
of er] endof
of e[ endof
of e] endof
of fa' endof
of fa- endof
of fa= endof
of fan' endof
of fan- endof
of fan= endof
of fang' endof
of fang- endof
of fang= endof
of fang[ endof
of fang] endof
of fan[ endof
of fan] endof
of fa[ endof
of fa] endof
of fei- endof
of fei= endof
of fei[ endof
of fei] endof
of fen' endof
of fen- endof
of fen= endof
of feng- endof
of feng= endof
of feng[ endof
of feng] endof
of fen[ endof
of fen] endof
of fo= endof
of fou[ endof
of fu' endof
of fu- endof
of fu= endof
of fu[ endof
of fu] endof
of ga- endof
of ga= endof
of gai- endof
of gai[ endof
of gai] endof
of gan- endof
of gang' endof
of gang- endof
of gang[ endof
of gang] endof
of gan[ endof
of gan] endof
of gau- endof
of gau[ endof
of gau] endof
of ga] endof
of ge' endof
of ge- endof
of ge= endof
of gei[ endof
of gen- endof
of gen= endof
of geng- endof
of geng[ endof
of geng] endof
of gen[ endof
of gen] endof
of ge[ endof
of ge] endof
of gou- endof
of gou[ endof
of gou] endof
of gu' endof
of gu- endof
of gu= endof
of gua- endof
of guai- endof
of guai[ endof
of guai] endof
of guan- endof
of guang- endof
of guang[ endof
of guang] endof
of guan[ endof
of guan] endof
of gua[ endof
of gua] endof
of guei' endof
of guei- endof
of guei[ endof
of guei] endof
of guen[ endof
of guen] endof
of gung- endof
of gung[ endof
of gung] endof
of guo' endof
of guo- endof
of guo= endof
of guo[ endof
of guo] endof
of gu[ endof
of gu] endof
of ha' endof
of ha- endof
of ha= endof
of hai' endof
of hai- endof
of hai= endof
of hai[ endof
of hai] endof
of han- endof
of han= endof
of hang- endof
of hang= endof
of hang] endof
of han[ endof
of han] endof
of hau- endof
of hau= endof
of hau[ endof
of hau] endof
of ha[ endof
of ha] endof
of he' endof
of he- endof
of he= endof
of hei- endof
of hen= endof
of heng' endof
of heng- endof
of heng= endof
of heng] endof
of hen[ endof
of hen] endof
of he] endof
of hou' endof
of hou- endof
of hou= endof
of hou[ endof
of hou] endof
of hu' endof
of hu- endof
of hu= endof
of hua' endof
of hua- endof
of hua= endof
of huai= endof
of huai] endof
of huan- endof
of huan= endof
of huang' endof
of huang- endof
of huang= endof
of huang[ endof
of huang] endof
of huan[ endof
of huan] endof
of hua[ endof
of hua] endof
of huei' endof
of huei- endof
of huei= endof
of huei[ endof
of huei] endof
of huen- endof
of huen= endof
of huen] endof
of hung- endof
of hung= endof
of hung[ endof
of hung] endof
of huo' endof
of huo- endof
of huo= endof
of huo[ endof
of huo] endof
of hu[ endof
of hu] endof
of i' endof
of i- endof
of i= endof
of ia' endof
of ia- endof
of ia= endof
of ian= endof
of iang- endof
of iang= endof
of iang[ endof
of iang] endof
of ian[ endof
of ian] endof
of iau- endof
of iau= endof
of iau[ endof
of iau] endof
of ia[ endof
of ia] endof
of ie' endof
of ie- endof
of ie= endof
of ie[ endof
of ie] endof
of in- endof
of in= endof
of ing' endof
of ing- endof
of ing= endof
of ing[ endof
of ing] endof
of in[ endof
of in] endof
of io' endof
of io- endof
of iou- endof
of iou= endof
of iou[ endof
of iou] endof
of i[ endof
of i] endof
of ja- endof
of ja= endof
of jai- endof
of jai= endof
of jai[ endof
of jai] endof
of jan- endof
of jang- endof
of jang[ endof
of jang] endof
of jan[ endof
of jan] endof
of jau- endof
of jau= endof
of jau[ endof
of jau] endof
of ja[ endof
of ja] endof
of je' endof
of je- endof
of je= endof
of jei] endof
of jen- endof
of jeng' endof
of jeng- endof
of jeng[ endof
of jeng] endof
of jen[ endof
of jen] endof
of je[ endof
of je] endof
of ji' endof
of ji- endof
of ji= endof
of jia' endof
of jia- endof
of jia= endof
of jian' endof
of jian- endof
of jiang- endof
of jiang[ endof
of jiang] endof
of jian[ endof
of jian] endof
of jiau- endof
of jiau= endof
of jiau[ endof
of jiau] endof
of jia[ endof
of jia] endof
of jie' endof
of jie- endof
of jie= endof
of jie[ endof
of jie] endof
of jin- endof
of jing' endof
of jing- endof
of jing[ endof
of jing] endof
of jin[ endof
of jin] endof
of jiou' endof
of jiou- endof
of jiou[ endof
of jiou] endof
of ji[ endof
of ji] endof
of jou- endof
of jou= endof
of jou[ endof
of jou] endof
of ju- endof
of ju= endof
of jua- endof
of juai- endof
of juai[ endof
of juai] endof
of juan- endof
of juang- endof
of juang[ endof
of juang] endof
of juan[ endof
of juan] endof
of jua[ endof
of juei- endof
of juei] endof
of jun- endof
of jung- endof
of jung[ endof
of jung] endof
of jun[ endof
of juo- endof
of juo= endof
of ju[ endof
of ju] endof
of jy' endof
of jy- endof
of jy= endof
of jyu- endof
of jyu= endof
of jyuan- endof
of jyuan[ endof
of jyuan] endof
of jyue- endof
of jyue= endof
of jyue[ endof
of jyue] endof
of jyun- endof
of jyung- endof
of jyung[ endof
of jyun] endof
of jyu[ endof
of jyu] endof
of jy[ endof
of jy] endof
of ka- endof
of kai- endof
of kai[ endof
of kai] endof
of kan- endof
of kang- endof
of kang= endof
of kang] endof
of kan[ endof
of kan] endof
of kau- endof
of kau[ endof
of kau] endof
of ka[ endof
of ke' endof
of ke- endof
of ke= endof
of kei- endof
of keng- endof
of ken[ endof
of ke[ endof
of ke] endof
of kou- endof
of kou[ endof
of kou] endof
of ku- endof
of kua- endof
of kuai' endof
of kuai[ endof
of kuai] endof
of kuan- endof
of kuang- endof
of kuang= endof
of kuang] endof
of kuan[ endof
of kua[ endof
of kua] endof
of kuei- endof
of kuei= endof
of kuei[ endof
of kuei] endof
of kuen- endof
of kuen[ endof
of kuen] endof
of kung- endof
of kung[ endof
of kung] endof
of kuo] endof
of ku[ endof
of ku] endof
of la' endof
of la- endof
of la= endof
of lai' endof
of lai= endof
of lai] endof
of lan= endof
of lang- endof
of lang= endof
of lang[ endof
of lang] endof
of lan[ endof
of lan] endof
of lau' endof
of lau- endof
of lau= endof
of lau[ endof
of lau] endof
of la[ endof
of la] endof
of le' endof
of lei- endof
of lei= endof
of lei[ endof
of lei] endof
of leng= endof
of leng[ endof
of leng] endof
of le] endof
of li' endof
of li- endof
of li= endof
of lian= endof
of liang' endof
of liang= endof
of liang[ endof
of liang] endof
of lian[ endof
of lian] endof
of liau- endof
of liau= endof
of liau[ endof
of liau] endof
of lia[ endof
of lie- endof
of lie[ endof
of lie] endof
of lin= endof
of ling- endof
of ling= endof
of ling[ endof
of ling] endof
of lin[ endof
of lin] endof
of liou- endof
of liou= endof
of liou[ endof
of liou] endof
of li[ endof
of li] endof
of lo' endof
of lou' endof
of lou- endof
of lou= endof
of lou[ endof
of lou] endof
of lu' endof
of lu- endof
of lu= endof
of luan= endof
of luan[ endof
of luan] endof
of luen- endof
of luen= endof
of luen] endof
of lung' endof
of lung- endof
of lung= endof
of lung[ endof
of lung] endof
of luo- endof
of luo= endof
of luo[ endof
of luo] endof
of lu[ endof
of lu] endof
of lyu= endof
of lyue] endof
of lyu[ endof
of lyu] endof
of ma' endof
of ma- endof
of ma= endof
of mai' endof
of mai= endof
of mai[ endof
of mai] endof
of man- endof
of man= endof
of mang= endof
of mang[ endof
of man[ endof
of man] endof
of mau' endof
of mau- endof
of mau= endof
of mau[ endof
of mau] endof
of ma[ endof
of ma] endof
of me' endof
of me= endof
of mei' endof
of mei= endof
of mei[ endof
of mei] endof
of men' endof
of men- endof
of men= endof
of meng- endof
of meng= endof
of meng[ endof
of meng] endof
of men] endof
of me] endof
of mi- endof
of mi= endof
of mian' endof
of mian= endof
of mian[ endof
of mian] endof
of miau- endof
of miau= endof
of miau[ endof
of miau] endof
of mie- endof
of mie] endof
of min= endof
of ming' endof
of ming= endof
of ming[ endof
of ming] endof
of min[ endof
of miou] endof
of mi[ endof
of mi] endof
of mo' endof
of mo- endof
of mo= endof
of mou- endof
of mou= endof
of mou[ endof
of mo[ endof
of mo] endof
of mu= endof
of mu[ endof
of mu] endof
of na' endof
of na- endof
of na= endof
of nai' endof
of nai[ endof
of nai] endof
of nan' endof
of nan- endof
of nan= endof
of nang- endof
of nang= endof
of nang[ endof
of nang] endof
of nan[ endof
of nan] endof
of nau' endof
of nau- endof
of nau= endof
of nau[ endof
of nau] endof
of na[ endof
of na] endof
of ne' endof
of nei[ endof
of nei] endof
of neng= endof
of nen] endof
of ne] endof
of ni- endof
of ni= endof
of nian- endof
of nian= endof
of niang' endof
of niang= endof
of niang] endof
of nian[ endof
of nian] endof
of niau[ endof
of niau] endof
of nie- endof
of nie= endof
of nie] endof
of nin= endof
of ning= endof
of ning[ endof
of ning] endof
of niou- endof
of niou= endof
of niou[ endof
of niou] endof
of ni[ endof
of ni] endof
of nou] endof
of nu= endof
of nuan[ endof
of nung= endof
of nung] endof
of nuo= endof
of nuo] endof
of nu[ endof
of nu] endof
of nyue] endof
of nyu[ endof
of nyu] endof
of o- endof
of o= endof
of ou- endof
of ou[ endof
of ou] endof
of o[ endof
of o] endof
of pa- endof
of pa= endof
of pai- endof
of pai= endof
of pai[ endof
of pai] endof
of pan- endof
of pan= endof
of pang- endof
of pang= endof
of pang[ endof
of pang] endof
of pan] endof
of pau- endof
of pau= endof
of pau[ endof
of pau] endof
of pa] endof
of pei- endof
of pei= endof
of pei] endof
of pen- endof
of pen= endof
of peng- endof
of peng= endof
of peng[ endof
of peng] endof
of pen] endof
of pi- endof
of pi= endof
of pian- endof
of pian= endof
of pian[ endof
of pian] endof
of piau- endof
of piau= endof
of piau[ endof
of piau] endof
of pie- endof
of pie[ endof
of pin- endof
of pin= endof
of ping- endof
of ping= endof
of pin[ endof
of pin] endof
of pi[ endof
of pi] endof
of po' endof
of po- endof
of po= endof
of pou- endof
of pou= endof
of pou[ endof
of po[ endof
of po] endof
of pu- endof
of pu= endof
of pu[ endof
of pu] endof
of ran= endof
of rang- endof
of rang= endof
of rang[ endof
of rang] endof
of ran[ endof
of rau= endof
of rau[ endof
of rau] endof
of ren' endof
of ren= endof
of reng- endof
of reng= endof
of ren[ endof
of ren] endof
of re[ endof
of re] endof
of rou= endof
of rou] endof
of ru= endof
of ruan[ endof
of ruei[ endof
of ruei] endof
of rung= endof
of rung[ endof
of run] endof
of ruo] endof
of ru[ endof
of ru] endof
of ry] endof
of sha- endof
of shai- endof
of shai[ endof
of shai] endof
of shan- endof
of shang' endof
of shang- endof
of shang[ endof
of shang] endof
of shan[ endof
of shan] endof
of shau' endof
of shau- endof
of shau= endof
of shau[ endof
of shau] endof
of sha[ endof
of sha] endof
of she- endof
of she= endof
of shei= endof
of shen' endof
of shen- endof
of shen= endof
of sheng' endof
of sheng- endof
of sheng= endof
of sheng[ endof
of sheng] endof
of shen[ endof
of shen] endof
of she[ endof
of she] endof
of shi' endof
of shi- endof
of shi= endof
of shia' endof
of shia- endof
of shia= endof
of shian- endof
of shian= endof
of shiang- endof
of shiang= endof
of shiang[ endof
of shiang] endof
of shian[ endof
of shian] endof
of shiau- endof
of shiau= endof
of shiau[ endof
of shiau] endof
of shia] endof
of shie' endof
of shie- endof
of shie= endof
of shie[ endof
of shie] endof
of shin- endof
of shin= endof
of shing' endof
of shing- endof
of shing= endof
of shing[ endof
of shing] endof
of shin] endof
of shiou- endof
of shiou[ endof
of shiou] endof
of shi[ endof
of shi] endof
of shou- endof
of shou[ endof
of shou] endof
of shu' endof
of shu- endof
of shu= endof
of shua- endof
of shuai- endof
of shuai[ endof
of shuai] endof
of shuan- endof
of shuang- endof
of shuang[ endof
of shuan] endof
of shua[ endof
of shua] endof
of shuei= endof
of shuei[ endof
of shuei] endof
of shun[ endof
of shun] endof
of shuo- endof
of shuo] endof
of shu[ endof
of shu] endof
of shy' endof
of shy- endof
of shy= endof
of shyu' endof
of shyu- endof
of shyu= endof
of shyuan- endof
of shyuan= endof
of shyuan[ endof
of shyuan] endof
of shyue- endof
of shyue= endof
of shyue[ endof
of shyue] endof
of shyun- endof
of shyun= endof
of shyung' endof
of shyung- endof
of shyung= endof
of shyun] endof
of shyu[ endof
of shyu] endof
of shy[ endof
of shy] endof
of ta- endof
of tai' endof
of tai- endof
of tai= endof
of tai] endof
of tan- endof
of tan= endof
of tang- endof
of tang= endof
of tang[ endof
of tang] endof
of tan[ endof
of tan] endof
of tau' endof
of tau- endof
of tau= endof
of tau[ endof
of tau] endof
of ta[ endof
of ta] endof
of tei- endof
of teng- endof
of teng= endof
of te] endof
of ti- endof
of ti= endof
of tian' endof
of tian- endof
of tian= endof
of tian[ endof
of tiau- endof
of tiau= endof
of tiau[ endof
of tiau] endof
of tie- endof
of tie[ endof
of tie] endof
of ting- endof
of ting= endof
of ting[ endof
of ti[ endof
of ti] endof
of tou' endof
of tou- endof
of tou= endof
of tou] endof
of tsa- endof
of tsai- endof
of tsai= endof
of tsai[ endof
of tsai] endof
of tsan- endof
of tsan= endof
of tsang- endof
of tsang= endof
of tsan[ endof
of tsan] endof
of tsau- endof
of tsau= endof
of tsau[ endof
of tsa[ endof
of tsen- endof
of tsen= endof
of tseng- endof
of tseng= endof
of tse] endof
of tsu- endof
of tsuan- endof
of tsuan= endof
of tsuan] endof
of tsuei- endof
of tsuei[ endof
of tsuei] endof
of tsuen- endof
of tsuen= endof
of tsuen[ endof
of tsuen] endof
of tsung- endof
of tsung= endof
of tsung] endof
of tsuo- endof
of tsuo= endof
of tsuo] endof
of tsu] endof
of tsy' endof
of tsy- endof
of tsy= endof
of tsy[ endof
of tsy] endof
of tu' endof
of tu- endof
of tu= endof
of tuan- endof
of tuan= endof
of tuei- endof
of tuei= endof
of tuei[ endof
of tuei] endof
of tun- endof
of tun= endof
of tung' endof
of tung- endof
of tung= endof
of tung[ endof
of tung] endof
of tun[ endof
of tun] endof
of tuo' endof
of tuo- endof
of tuo= endof
of tuo[ endof
of tuo] endof
of tu[ endof
of tu] endof
of u' endof
of u- endof
of u= endof
of ua' endof
of ua- endof
of ua= endof
of uai' endof
of uai- endof
of uai[ endof
of uai] endof
of uan- endof
of uan= endof
of uang' endof
of uang- endof
of uang= endof
of uang[ endof
of uang] endof
of uan[ endof
of uan] endof
of ua[ endof
of ua] endof
of uei' endof
of uei- endof
of uei= endof
of uei[ endof
of uei] endof
of uen' endof
of uen- endof
of uen= endof
of uen[ endof
of uen] endof
of ung- endof
of ung[ endof
of ung] endof
of uo- endof
of uo[ endof
of uo] endof
of u[ endof
of u] endof
of xa- endof
of xai- endof
of xai] endof
of xan- endof
of xang- endof
of xang[ endof
of xang] endof
of xan[ endof
of xan] endof
of xau- endof
of xau[ endof
of xau] endof
of xa[ endof
of xa] endof
of xen- endof
of xeng- endof
of xe] endof
of xou' endof
of xou- endof
of xou[ endof
of xou] endof
of xu' endof
of xu- endof
of xu= endof
of xuan- endof
of xuan] endof
of xuei- endof
of xuei= endof
of xuei[ endof
of xuei] endof
of xun- endof
of xung- endof
of xung[ endof
of xung] endof
of xun[ endof
of xuo' endof
of xuo- endof
of xuo[ endof
of xu] endof
of xy' endof
of xy- endof
of xy[ endof
of xy] endof
of you0 endof
of yu' endof
of yu- endof
of yu= endof
of yuan- endof
of yuan= endof
of yuan[ endof
of yuan] endof
of yue- endof
of yue] endof
of yun- endof
of yun= endof
of yung- endof
of yung= endof
of yung[ endof
of yung] endof
of yun[ endof
of yun] endof
of yu[ endof
of yu] endof

of za- endof
of za= endof
of zai' endof
of zai- endof
of zai[ endof
of zai] endof
of zan' endof
of zan- endof
of zan= endof
of zang- endof
of zang[ endof
of zang] endof
of zan[ endof
of zan] endof
of zau- endof
of zau= endof
of zau[ endof
of zau] endof
of za[ endof
of ze= endof
of zei= endof
of zeng- endof
of zeng] endof
of zen[ endof
of zen] endof
of ze] endof
of zou- endof
of zou[ endof
of zou] endof
of zu- endof
of zu= endof
of zuan- endof
of zuan[ endof
of zuan] endof
of zui[ endof
of zui] endof
of zun- endof
of zung- endof
of zung[ endof
of zung] endof
of zun[ endof

ascii o of
 case
  ascii - of zuo- endof
  ascii = of zuo= endof
  ascii [ of zuo[ endof
  ascii ] of zuo] endof
 end case
 
ascii u of
 case
  of zu[ endof 
  of zu[ endof
 end case

ascii y of
 case
  ascii ' of zy' endof
  ascii - of zy- endof
  ascii [ of zy[ endof
  ascii ] of zy] endof
 end case
 
end case 